In [1]:
import duckdb
import polars as pl
import pandas as pd
import json
import os

In [14]:
import duckdb
import polars as pl
from IPython.display import display


silver_db_path = (
    "/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/silver/dev/api_modrinth_com.duckdb"
)
bronze_db_path=("/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/api_modrinth_com.duckdb")


with duckdb.connect(
    silver_db_path,
    read_only=True,
) as silver_con:

    tables = silver_con.execute(
        """
        SHOW TABLES
        """
    ).pl()

    display(tables)

shape: (4, 1)
┌───────────────────────────┐
│ name                      │
│ ---                       │
│ str                       │
╞═══════════════════════════╡
│ base_api_file_tables      │
│ modrinth_project_listings │
│ modrinth_project_versions │
│ test_bronze_connection    │
└───────────────────────────┘

In [4]:
with duckdb.connect(
    silver_db_path,
    read_only=True,
) as silver_con:

    silver_df = silver_con.execute(
        """
        SELECT *
        FROM main.modrinth_project_listings
        LIMIT 25
        """
    ).pl()


with pl.Config(
    tbl_rows=100,
    tbl_cols=100,
):
    display(silver_df)

shape: (25, 30)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ run ┆ pro ┆ pro ┆ has ┆ c_p ┆ all ┆ slu ┆ aut ┆ aut ┆ org ┆ org ┆ tit ┆ des ┆ cat ┆ dis ┆ ver ┆ dow ┆ fol ┆ ico ┆ dat ┆ dat ┆ lat ┆ lic ┆ cli ┆ ser ┆ env ┆ dis ┆ gal ┆ fea ┆ col │
│ _id ┆ jec ┆ jec ┆ hed ┆ ull ┆ _pr ┆ g   ┆ hor ┆ hor ┆ ani ┆ ani ┆ le  ┆ cri ┆ ego ┆ pla ┆ sio ┆ nlo ┆ low ┆ n_u ┆ e_c ┆ e_m ┆ est ┆ ens ┆ ent ┆ ver ┆ iro ┆ clo ┆ ler ┆ tur ┆ or  │
│ --- ┆ t_t ┆ t_i ┆ _pa ┆ _ti ┆ oje ┆ --- ┆ --- ┆ _id ┆ zat ┆ zat ┆ --- ┆ pti ┆ rie ┆ y_c ┆ ns  ┆ ads ┆ s   ┆ rl  ┆ rea ┆ odi ┆ _ve ┆ e   ┆ _si ┆ _si ┆ nme ┆ sur ┆ y   ┆ ed_ ┆ --- │
│ str ┆ ype ┆ d   ┆ ylo ┆ mes ┆ ct_ ┆ str ┆ str ┆ --- ┆ ion ┆ ion ┆ str ┆ on  ┆ s   ┆ ate ┆ --- ┆ --- ┆ --- ┆ --- ┆ ted ┆ fie ┆ rsi ┆ --- ┆ de  ┆ de  ┆ nt  ┆ e_t ┆ --- ┆ gal ┆ i64 │
│     ┆ --- ┆ --- ┆ ad  ┆ tam ┆ typ ┆     ┆     ┆ str ┆ --- ┆ _id ┆     ┆ --- ┆ --- ┆ gor ┆ lis ┆ i64 ┆ i64 ┆ str ┆ --- ┆ d   ┆ on  ┆ str ┆ --- ┆ --- ┆ --- ┆ ype ┆ lis ┆ ler ┆     │
│     ┆ str ┆ str ┆ --- ┆ p_u ┆ es  ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ str ┆ lis ┆ ies ┆ t[s ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ lis ┆ s   ┆ t[s ┆ y   ┆     │
│     ┆     ┆     ┆ str ┆ tc  ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ t[s ┆ --- ┆ tr] ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t[s ┆ --- ┆ tr] ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ lis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆ lis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆ lis ┆     ┆ str ┆     │
│     ┆     ┆     ┆     ┆ dat ┆ t[s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ eti ┆ tr] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ μs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ Ame ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ric ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ a/L ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ os_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ Ang ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ele ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ s]  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 823 ┆ res ┆ m7q ┆ bab ┆ 202 ┆ ["r ┆ pvp ┆ Max ┆ roL ┆ nul ┆ nul ┆ PvP ┆ thi ┆ ["c ┆ ["c ┆ ["1 ┆ 132 ┆ 0   ┆ htt ┆ 202 ┆ 202 ┆ MJU ┆ MIT ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ nul ┆ 447 │
│ 511 ┆ our ┆ ejE ┆ baa ┆ 6-0 ┆ eso ┆ _te ┆ oSh ┆ NSx ┆ l   ┆ l   ┆ tex ┆ s   ┆ omb ┆ omb ┆ .21 ┆     ┆     ┆ ps: ┆ 6-0 ┆ 6-0 ┆ tOU ┆     ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ l   ┆ 392 │
│ 4d- ┆ cep ┆ GN  ┆ 8e0 ┆ 8-2 ┆ urc ┆ xtu ┆ ort ┆ rL  ┆     ┆     ┆ tur ┆ tex ┆ at" ┆ at" ┆ .7" ┆     ┆     ┆ //c ┆ 3-1 ┆ 3-3 ┆ qE  ┆     ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆     ┆ 4   │
│ 455 ┆ ack ┆     ┆ af5 ┆ 6   ┆ epa ┆ res ┆ s   ┆     ┆     ┆     ┆ es  ┆ tur ┆ ,   ┆ ,   ┆ ,   ┆     ┆     ┆ dn. ┆ 2T0 ┆ 1T1 ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆ /cd ┆     ┆     │
│ f-4 ┆     ┆     ┆ 3c1 ┆ 06: ┆ ck" ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ "mi ┆ "mi ┆ "1. ┆     ┆     ┆ mod ┆ 4:5 ┆ 6:2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ n.m ┆     ┆     │
│ 360 ┆     ┆     ┆ eef ┆ 01: ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆ pac ┆ nec ┆ nec ┆ 21. ┆     ┆     ┆ rin ┆ 0:1 ┆ 7:5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ odr ┆     ┆     │
│ -bb ┆     ┆     ┆ f3b ┆ 38. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆ raf ┆ raf ┆ 8"] ┆     ┆     ┆ th. ┆ 5.3 ┆ 8.7 ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     │
│ 4d- ┆     ┆     ┆ bc0 ┆ 676 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆ t"] ┆ t"] ┆     ┆     ┆     ┆ com ┆ 300 ┆ 231 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.c ┆     ┆     │
│ dc5 ┆     ┆     ┆ 0e0 ┆ 880 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lud ┆     ┆     ┆     ┆     ┆     ┆ /da ┆ 65+ ┆ 57+ ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆     ┆     │
│ c73 ┆     ┆     ┆ 075 ┆ PDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bet ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 823 ┆ res ┆ mED ┆ dd2 ┆ 202 ┆ ["r ┆ dev ┆ The ┆ BRx ┆ nul ┆ nul ┆ Dev ┆ A   ┆ ["1 ┆ ["1 ┆ ["1 ┆ 434 ┆ 8   ┆ htt ┆ 202 ┆ 202 ┆ olL ┆ CC- ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ htt ┆ 243 │
│ 511 ┆ our ┆ YuN ┆ d81 ┆ 6-0 ┆ eso ┆ s-b ┆ One ┆ K2A ┆ l   ┆ l   ┆ 's  ┆ res ┆ 6x" ┆ 6x" ┆ .20 ┆ 3   ┆     ┆ ps: ┆ 5-0 ┆ 5-0 ┆ ils ┆ BY- ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ ps: ┆ 331 │
│ 4d- ┆ cep ┆ NP  ┆ b81 ┆ 8-2 ┆ urc ┆ ett ┆ Tru ┆ nN  ┆     ┆     ┆ Bet ┆ our ┆ ,   ┆ ,   ┆ .6" ┆     ┆     ┆ //c ┆ 5-1 ┆ 5-1 ┆ 98  ┆ 4.0 ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆ //c ┆ 4   │
│ 455 ┆ ack ┆     ┆ 2a8 ┆ 6   ┆ epa ┆ er- ┆ eDe ┆     ┆     ┆     ┆ ter ┆ ce- ┆ "gu ┆ "gu ┆ ,   ┆     ┆     ┆ dn. ┆ 2T0 ┆ 0T2 ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆ /cd ┆ dn. ┆     │
│ f-4 ┆     ┆     ┆ 501 ┆ 06: ┆ ck" ┆ arm ┆ v   ┆     ┆     ┆     ┆ Arm ┆ pac ┆ i", ┆ i", ┆ "1. ┆     ┆     ┆ mod ┆ 6:2 ┆ 0:3 ┆     ┆     ┆     ┆     ┆     ┆     ┆ n.m ┆ mod ┆     │
│ 360 ┆     ┆     ┆ 051 ┆ 01: ┆ ]   ┆ or- ┆     ┆     ┆     ┆     ┆ or  ┆ k   ┆ …   ┆ …   ┆ 21" ┆     ┆     ┆ rin ┆ 6:5 ┆ 5:2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ odr ┆ rin ┆     │
│ -bb ┆     ┆     ┆ 6d7 ┆ 09. ┆     ┆ ico ┆     ┆     ┆     ┆     ┆ Ico ┆ tha ┆ "va ┆ "va ┆ , … ┆     ┆     ┆ th. ┆ 5.7 ┆ 1.7 ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆ th. ┆     │
│ 4d- ┆     ┆     ┆ 013 ┆ 467 ┆     ┆ ns- ┆     ┆     ┆     ┆     ┆ ns  ┆ t   ┆ nil ┆ nil ┆ "1. ┆     ┆     ┆ com ┆ 602 ┆ 065 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.c ┆ com ┆     │
│ dc5 ┆     ┆     ┆ d25 ┆ 632 ┆     ┆ net ┆     ┆     ┆     ┆     ┆ -   ┆ rew ┆ la- ┆ la- ┆ 21. ┆     ┆     ┆ /da ┆ 16+ ┆ 05+ ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆ /da ┆     │
│ c73 ┆     ┆     ┆ 867 ┆ PDT ┆     ┆ her ┆     ┆     ┆     ┆     ┆ Net ┆ ork ┆ lik ┆ lik ┆ 5"] ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆ ta/ ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆ …   ┆ s   ┆ e…  ┆ e…  ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 823 ┆ res ┆ mEf ┆ fec ┆ 202 ┆ ["r ┆ bet ┆ exe ┆ pes ┆ nul ┆ nul ┆ bet ┆ Sma ┆ ["1 ┆ ["1 ┆ ["2 ┆ 115 ┆ 1   ┆ htt ┆ 202 ┆ 202 ┆ C0g ┆ Lic ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ htt ┆ 795 │
│ 511 ┆ our ┆ jWO ┆ 6ec ┆ 6-0 ┆ eso ┆ ter ┆ pvp ┆ Htf ┆ l   ┆ l   ┆ ter ┆ lle ┆ 6x" ┆ 6x" ┆ 4w1 ┆ 0   ┆     ┆ ps: ┆ 6-0 ┆ 6-0 ┆ rwu ┆ ens ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ ps: ┆ 676 │
│ 4d- ┆ cep ┆ R4  ┆ a0a ┆ 8-2 ┆ urc ┆ -pv ┆ 142 ┆ Df  ┆     ┆     ┆ pvp ┆ r   ┆ ,   ┆ ,   ┆ 8a" ┆     ┆     ┆ //c ┆ 5-1 ┆ 5-0 ┆ 56  ┆ eRe ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆ //c ┆     │
│ 455 ┆ ack ┆     ┆ 12a ┆ 6   ┆ epa ┆ p-t ┆     ┆     ┆     ┆     ┆ tex ┆ fir ┆ "co ┆ "co ┆ ,   ┆     ┆     ┆ dn. ┆ 6T0 ┆ 1T1 ┆     ┆ f-A ┆     ┆ ed  ┆     ┆     ┆ /cd ┆ dn. ┆     │
│ f-4 ┆     ┆     ┆ eeb ┆ 06: ┆ ck" ┆ ext ┆     ┆     ┆     ┆     ┆ tur ┆ e,t ┆ mba ┆ mba ┆ "24 ┆     ┆     ┆ mod ┆ 4:3 ┆ 9:1 ┆     ┆ ll- ┆     ┆     ┆     ┆     ┆ n.m ┆ mod ┆     │
│ 360 ┆     ┆     ┆ 039 ┆ 01: ┆ ]   ┆ ure ┆     ┆     ┆     ┆     ┆ es  ┆ ote ┆ t", ┆ t", ┆ w19 ┆     ┆     ┆ rin ┆ 6:5 ┆ 5:2 ┆     ┆ Rig ┆     ┆     ┆     ┆     ┆ odr ┆ rin ┆     │
│ -bb ┆     ┆     ┆ 308 ┆ 14. ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ m   ┆ …   ┆ …   ┆ a", ┆     ┆     ┆ th. ┆ 1.4 ┆ 3.6 ┆     ┆ hts ┆     ┆     ┆     ┆     ┆ int ┆ th. ┆     │
│ 4d- ┆     ┆     ┆ 32e ┆ 401 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆ "va ┆ "mi ┆ …   ┆     ┆     ┆ com ┆ 684 ┆ 960 ┆     ┆ -Re ┆     ┆     ┆     ┆     ┆ h.c ┆ com ┆     │
│ dc5 ┆     ┆     ┆ 8d0 ┆ 879 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ shi ┆ nil ┆ nec ┆ "26 ┆     ┆     ┆ /da ┆ 03+ ┆ 43+ ┆     ┆ ser ┆     ┆     ┆     ┆     ┆ om/ ┆ /da ┆     │
│ c73 ┆     ┆     ┆ 7d6 ┆ PDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eld ┆ la- ┆ raf ┆ .2" ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆ ved ┆     ┆     ┆     ┆     ┆ dat ┆ ta/ ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,…  ┆ l…  ┆ t…  ┆ ]   ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     │
│ 823 ┆ res ┆ mKU ┆ 967 ┆ 202 ┆ ["r ┆ fai ┆ Po3 ┆ YIz ┆ nul ┆ nul ┆ Fai ┆ Fai ┆ ["3 ┆ ["3 ┆ ["1 ┆ 433 ┆ 6   ┆ htt ┆ 202 ┆ 202 ┆ 9yf ┆ Lic ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ nul ┆ 847 │
│ 511 ┆ our ┆ RGh ┆ df7 ┆ 6-0 ┆ eso ┆ thf ┆ ste ┆ R26 ┆ l   ┆ l   ┆ thf ┆ thf ┆ 2x" ┆ 2x" ┆ .21 ┆ 3   ┆     ┆ ps: ┆ 4-1 ┆ 6-0 ┆ FWo ┆ ens ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ l   ┆ 724 │
│ 4d- ┆ cep ┆ ev  ┆ 772 ┆ 8-2 ┆ urc ┆ ul- ┆ ll3 ┆ 1G  ┆     ┆     ┆ ul  ┆ ul  ┆ ,   ┆ ,   ┆ .1" ┆     ┆     ┆ //c ┆ 2-0 ┆ 4-0 ┆ rI  ┆ eRe ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆     ┆ 8   │
│ 455 ┆ ack ┆     ┆ c86 ┆ 6   ┆ epa ┆ ser ┆ d   ┆     ┆     ┆     ┆ Ser ┆ tex ┆ "de ┆ "fo ┆ ,   ┆     ┆     ┆ dn. ┆ 8T0 ┆ 8T1 ┆     ┆ f-A ┆     ┆ ed  ┆     ┆     ┆ /cd ┆     ┆     │
│ f-4 ┆     ┆     ┆ 590 ┆ 06: ┆ ck" ┆ if  ┆     ┆     ┆     ┆     ┆ if  ┆ tur ┆ cor ┆ nts ┆ "1. ┆     ┆     ┆ mod ┆ 0:2 ┆ 8:2 ┆     ┆ ll- ┆     ┆     ┆     ┆     ┆ n.m ┆     ┆     │
│ 360 ┆     ┆     ┆ 4f6 ┆ 01: ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ ati ┆ ",  ┆ 21. ┆     ┆     ┆ rin ┆ 3:4 ┆ 0:3 ┆     ┆ Rig ┆     ┆     ┆     ┆     ┆ odr ┆     ┆     │
│ -bb ┆     ┆     ┆ aab ┆ 09. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pac ┆ on" ┆ …   ┆ 2", ┆     ┆     ┆ th. ┆ 1.1 ┆ 2.8 ┆     ┆ hts ┆     ┆     ┆     ┆     ┆ int ┆     ┆     │
│ 4d- ┆     ┆     ┆ c67 ┆ 467 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆ , … ┆ "si ┆ …   ┆     ┆     ┆ com ┆ 642 ┆ 954 ┆     ┆ -Re ┆     ┆     ┆     ┆     ┆ h.c ┆     ┆     │
│ dc5 ┆     ┆     ┆ f5d ┆ 632 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onl ┆ "va ┆ mpl ┆ "26 ┆     ┆     ┆ /da ┆ 92+ ┆ 79+ ┆     ┆ ser ┆     ┆     ┆     ┆     ┆ om/ ┆     ┆     │
│ c73 ┆     ┆     ┆ e1f ┆ PDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y.  ┆ nil ┆ ist ┆ .1. ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆ ved ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tr… ┆ …   ┆ ic… ┆ 1…  ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     │
│ 823 ┆ res ┆ mMf ┆ 7c4 ┆ 202 ┆ ["r ┆ no- ┆ Amz ┆ lZ5 ┆ nul ┆ nul ┆ No  ┆ A   ┆ ["a ┆ ["a ┆ ["1 ┆ 5   ┆ 0   ┆ htt ┆ 202 ┆ 202 ┆ znD ┆ GPL ┆ req ┆ uns ┆ []  ┆ []  ┆ []  ┆ nul ┆ 940 │
│ 511 ┆ our ┆ ToR ┆ 15d ┆ 6-0 ┆ eso ┆ mor ┆ in  ┆ xad ┆ l   ┆ l   ┆ Mor ┆ Res ┆ udi ┆ udi ┆ .21 ┆     ┆     ┆ ps: ┆ 6-0 ┆ 6-0 ┆ eUj ┆ -3. ┆ uir ┆ upp ┆     ┆     ┆     ┆ l   ┆ 400 │
│ 4d- ┆ cep ┆ Jr  ┆ a66 ┆ 8-2 ┆ urc ┆ e-r ┆     ┆ vL  ┆     ┆     ┆ e   ┆ our ┆ o", ┆ o", ┆ .5" ┆     ┆     ┆ //c ┆ 8-2 ┆ 8-2 ┆ HF  ┆ 0-o ┆ ed  ┆ ort ┆     ┆     ┆     ┆     ┆ 4   │
│ 455 ┆ ack ┆     ┆ a67 ┆ 6   ┆ epa ┆ eal ┆     ┆     ┆     ┆     ┆ Rea ┆ ce  ┆ "mi ┆ "mi ┆ ,   ┆     ┆     ┆ dn. ┆ 5T0 ┆ 4T0 ┆     ┆ r-l ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     │
│ f-4 ┆     ┆     ┆ 883 ┆ 06: ┆ ck" ┆ -an ┆     ┆     ┆     ┆     ┆ l   ┆ Pac ┆ nec ┆ nec ┆ "1. ┆     ┆     ┆ mod ┆ 7:3 ┆ 0:0 ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 360 ┆     ┆     ┆ 20c ┆ 02: ┆ ]   ┆ ima ┆     ┆     ┆     ┆     ┆ Ani ┆ k   ┆ raf ┆ raf ┆ 21. ┆     ┆     ┆ rin ┆ 0:2 ┆ 7:5 ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ -bb ┆     ┆     ┆ 62a ┆ 02. ┆     ┆ l-s ┆     ┆     ┆     ┆     ┆ mal ┆ tha ┆ t", ┆ t", ┆ 6", ┆     ┆     ┆ th. ┆ 6.8 ┆ 9.3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4d- ┆     ┆     ┆ 2e3 ┆ 863 ┆     ┆ oun ┆     ┆     ┆     ┆     ┆ Sou ┆ t   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆ com ┆ 450 ┆ 616 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ dc5 ┆     ┆     ┆ 1ca ┆ 154 ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆ nds ┆ rem ┆ "va ┆ "va ┆ "26 ┆     ┆     ┆ /da ┆ 01+ ┆ 93+ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ c73 ┆     ┆     ┆ a5b ┆ PDT ┆     ┆     ┆     ┆     ┆     ┆     ┆ !   ┆ ove ┆ ni… ┆ ni… ┆ .2" ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ]   ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 823 ┆ res ┆ mMp ┆ 7c1 ┆ 202 ┆ ["r ┆ enh ┆ FIR ┆ Rpi ┆ nul ┆ nul ┆ Enh ┆ Mak ┆ ["1 ┆ ["c ┆ ["1 ┆ 961 ┆ 1   ┆ htt ┆ 202 ┆ 202 ┆ UYy ┆ MIT ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ nul ┆ 263 │
│ 511 ┆ our ┆ 9Ug ┆ f9b ┆ 6-0 ┆ eso ┆ anc ┆ EST ┆ HZX ┆ l   ┆ l   ┆ anc ┆ ing ┆ 6x" ┆ omb ┆ .7. ┆ 5   ┆     ┆ ps: ┆ 4-0 ┆ 4-0 ┆ Mob ┆     ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ l   ┆ 172 │
│ 4d- ┆ cep ┆ xd  ┆ 324 ┆ 8-2 ┆ urc ┆ ed- ┆ AR0 ┆ SC  ┆     ┆     ┆ ed  ┆ Min ┆ ,   ┆ at" ┆ 10" ┆     ┆     ┆ //c ┆ 2-2 ┆ 2-1 ┆ Ia  ┆     ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆     ┆     │
│ 455 ┆ ack ┆     ┆ e96 ┆ 6   ┆ epa ┆ swo ┆ 9_1 ┆     ┆     ┆     ┆ Swo ┆ ecr ┆ "co ┆ ,   ┆ ,   ┆     ┆     ┆ dn. ┆ 0T0 ┆ 0T1 ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆ /cd ┆     ┆     │
│ f-4 ┆     ┆     ┆ ba5 ┆ 06: ┆ ck" ┆ rds ┆ 0   ┆     ┆     ┆     ┆ rds ┆ aft ┆ mba ┆ "mi ┆ "1. ┆     ┆     ┆ mod ┆ 7:3 ┆ 7:1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ n.m ┆     ┆     │
│ 360 ┆     ┆     ┆ bb2 ┆ 01: ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆ Swo ┆ t", ┆ nec ┆ 8", ┆     ┆     ┆ rin ┆ 2:4 ┆ 6:2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ odr ┆     ┆     │
│ -bb ┆     ┆     ┆ aeb ┆ 07. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rds ┆ …   ┆ raf ┆ …   ┆     ┆     ┆ th. ┆ 8.4 ┆ 7.8 ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     │
│ 4d- ┆     ┆     ┆ 4c5 ┆ 768 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bet ┆ "va ┆ t", ┆ "1. ┆     ┆     ┆ com ┆ 156 ┆ 738 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.c ┆     ┆     │
│ dc5 ┆     ┆     ┆ 1a3 ┆ 637 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter ┆ nil ┆ …   ┆ 20. ┆     ┆     ┆ /da ┆ 37+ ┆ 90+ ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆     ┆     │
│ c73 ┆     ┆     ┆ 26b ┆ PDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ la- ┆ "th ┆ 4"] ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l…  ┆ e…  ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     │
│ 823 ┆ res ┆ mrr ┆ 3f6 ┆ 202 ┆ ["r ┆ bar ┆ Pri ┆ S6j ┆ nul ┆ nul ┆ Bar ┆ Red ┆ ["1 ┆ ["1 ┆ ["1 ┆ 327 ┆ 24  ┆ htt ┆ 202 ┆ 202 ┆ WXn ┆ Lic ┆ req ┆ uns ┆ []  ┆ []  ┆ []  ┆ htt ┆ 836 │
│ 511 ┆ our ┆ wMD ┆ 9d2 ┆ 6-0 ┆ eso ┆ e-b ┆ ncP ┆ d94 ┆ l   ┆ l   ┆ e   ┆ esi ┆ 6x" ┆ 6x" ┆ .20 ┆ 23  ┆     ┆ ps: ┆ 4-0 ┆ 6-0 ┆ JC4 ┆ ens ┆ uir ┆ upp ┆     ┆     ┆     ┆ ps: ┆ 692 │
│ 4d- ┆ cep ┆ 47  ┆ 376 ┆ 8-2 ┆ urc ┆ one ┆ ars ┆ Vf  ┆     ┆     ┆ Bon ┆ gns ┆ ,   ┆ ,   ┆ ",  ┆     ┆     ┆ //c ┆ 8-1 ┆ 1-2 ┆ 2b  ┆ eRe ┆ ed  ┆ ort ┆     ┆     ┆     ┆ //c ┆     │
│ 455 ┆ ack ┆     ┆ 498 ┆ 6   ┆ epa ┆ s-x ┆ hia ┆     ┆     ┆     ┆ es  ┆ arm ┆ "it ┆ "mi ┆ "1. ┆     ┆     ┆ dn. ┆ 9T2 ┆ 2T1 ┆     ┆ f-A ┆     ┆ ed  ┆     ┆     ┆     ┆ dn. ┆     │
│ f-4 ┆     ┆     ┆ 269 ┆ 06: ┆ ck" ┆ -ar ┆     ┆     ┆     ┆     ┆ x   ┆ or  ┆ ems ┆ nec ┆ 20. ┆     ┆     ┆ mod ┆ 1:5 ┆ 3:1 ┆     ┆ ll- ┆     ┆     ┆     ┆     ┆     ┆ mod ┆     │
│ 360 ┆     ┆     ┆ d60 ┆ 01: ┆ ]   ┆ mor ┆     ┆     ┆     ┆     ┆ Arm ┆ tri ┆ ",  ┆ raf ┆ 1", ┆     ┆     ┆ rin ┆ 0:1 ┆ 1:5 ┆     ┆ Rig ┆     ┆     ┆     ┆     ┆     ┆ rin ┆     │
│ -bb ┆     ┆     ┆ 614 ┆ 06. ┆     ┆ -tr ┆     ┆     ┆     ┆     ┆ or  ┆ m   ┆ "mi ┆ t"] ┆ …   ┆     ┆     ┆ th. ┆ 4.4 ┆ 1.9 ┆     ┆ hts ┆     ┆     ┆     ┆     ┆     ┆ th. ┆     │
│ 4d- ┆     ┆     ┆ 4e0 ┆ 601 ┆     ┆ im- ┆     ┆     ┆     ┆     ┆ Tri ┆ ite ┆ nec ┆     ┆ "1. ┆     ┆     ┆ com ┆ 809 ┆ 288 ┆     ┆ -Re ┆     ┆     ┆     ┆     ┆     ┆ com ┆     │
│ dc5 ┆     ┆     ┆ a9b ┆ 532 ┆     ┆ ite ┆     ┆     ┆     ┆     ┆ m   ┆ m   ┆ raf ┆     ┆ 21. ┆     ┆     ┆ /da ┆ 95+ ┆ 64+ ┆     ┆ ser ┆     ┆     ┆     ┆     ┆     ┆ /da ┆     │
│ c73 ┆     ┆     ┆ 1e3 ┆ PDT ┆     ┆ m-f ┆     ┆     ┆     ┆     ┆ Ite ┆ tex ┆ t"] ┆     ┆ 11" ┆     ┆     ┆ ta/ ┆ 00: ┆ 00: ┆     ┆ ved ┆     ┆     ┆     ┆     ┆     ┆ ta/ ┆     │
│ …   ┆     ┆     ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆ m   ┆ t…  ┆     ┆     ┆ …   ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ F…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 823 ┆ res ┆ n4n ┆ 96a ┆ 202 ┆ ["r ┆ hyp ┆ Ian ┆ lrs ┆ nul ┆ nul ┆ Hyp ┆ A   ┆ ["5 ┆ ["5 ┆ ["1 ┆ 309 ┆ 0   ┆ htt ┆ 202 ┆ 202 ┆ doG ┆ Lic ┆ req ┆ uns ┆ []  ┆ []  ┆ ["h ┆ htt ┆ 768 │
│ 511 ┆ our ┆ gRl ┆ 1f2 ┆ 6-0 ┆ eso ┆ not ┆ Cab ┆ whh ┆ l   ┆ l   ┆ not ┆ cus ┆ 12x ┆ 12x ┆ .20 ┆     ┆     ┆ ps: ┆ 6-0 ┆ 6-0 ┆ m9B ┆ ens ┆ uir ┆ upp ┆     ┆     ┆ ttp ┆ ps: ┆ 268 │
│ 4d- ┆ cep ┆ ll  ┆ 52d ┆ 8-2 ┆ urc ┆ ic- ┆ il  ┆ qC  ┆     ┆     ┆ ic  ┆ tom ┆ +", ┆ +", ┆ ",  ┆     ┆     ┆ //c ┆ 7-3 ┆ 7-2 ┆ pC  ┆ eRe ┆ ed  ┆ ort ┆     ┆     ┆ s:/ ┆ //c ┆ 2   │
│ 455 ┆ ack ┆     ┆ 861 ┆ 6   ┆ epa ┆ eye ┆     ┆     ┆     ┆     ┆ Eye ┆ bac ┆ "gu ┆ "gu ┆ "1. ┆     ┆     ┆ dn. ┆ 0T1 ┆ 8T0 ┆     ┆ f-A ┆     ┆ ed  ┆     ┆     ┆ /cd ┆ dn. ┆     │
│ f-4 ┆     ┆     ┆ 62a ┆ 06: ┆ ck" ┆ s-b ┆     ┆     ┆     ┆     ┆ s   ┆ kgr ┆ i", ┆ i", ┆ 20. ┆     ┆     ┆ mod ┆ 9:0 ┆ 9:5 ┆     ┆ ll- ┆     ┆     ┆     ┆     ┆ n.m ┆ mod ┆     │
│ 360 ┆     ┆     ┆ 4b7 ┆ 01: ┆ ]   ┆ ack ┆     ┆     ┆     ┆     ┆ Bac ┆ oun ┆ …   ┆ …   ┆ 1", ┆     ┆     ┆ rin ┆ 7:4 ┆ 8:4 ┆     ┆ Rig ┆     ┆     ┆     ┆     ┆ odr ┆ rin ┆     │
│ -bb ┆     ┆     ┆ 386 ┆ 28. ┆     ┆ gro ┆     ┆     ┆     ┆     ┆ kgr ┆ d   ┆ "si ┆ "si ┆ …   ┆     ┆     ┆ th. ┆ 1.9 ┆ 4.1 ┆     ┆ hts ┆     ┆     ┆     ┆     ┆ int ┆ th. ┆     │

In [7]:
with duckdb.connect(
    silver_db_path,
    read_only=True,
) as con:
    print(
        con.execute(
            """
            SELECT
                project_type,
                COUNT(*) AS project_count,
                MAX(c_pull_timestamp_utc)
                    AS latest_processed_timestamp

            FROM modrinth_project_listings

            GROUP BY project_type

            ORDER BY project_type
            """
        ).df()
    )

            project_type  project_count       latest_processed_timestamp
0               datapack          14367 2026-08-26 06:03:34.385572-07:00
1  minecraft_java_server           2027 2026-08-26 06:03:35.484656-07:00
2                    mod          73887 2026-08-26 06:00:44.010241-07:00
3                modpack          18151 2026-08-26 06:01:05.364387-07:00
4                 plugin          17116 2026-08-26 06:03:22.503771-07:00
5           resourcepack          33795 2026-08-26 06:02:02.863154-07:00
6                 shader            837 2026-08-26 06:02:03.585893-07:00

NameError: name '__file__' is not defined

In [21]:
with duckdb.connect(
    bronze_db_path,
    read_only=True,
) as con:
    df = (
        con.execute(
            """
            SELECT
                l.run_id,
                l.project_type,
                COUNT(b.project_id) AS matching_rows

            FROM main.ingestion_log AS l

            LEFT JOIN main.modrinth_project_listings AS b
                ON l.run_id = b.run_id
                AND l.project_type = b.project_type

            WHERE LOWER(TRIM(l.status)) = 'success'

            GROUP BY
                l.run_id,
                l.project_type

            ORDER BY
                l.project_type,
                l.run_id
            """
        ).df()
    )
df

                                  run_id project_type  matching_rows
0   0a0fa12b-0c4d-415c-bad1-9d83d97629e4     datapack          14164
1   21f1554d-0f8b-423c-b708-97f80453e17f     datapack          14165
2   3b497402-8609-42e3-9304-38aadd1066f4     datapack          14166
3   63a1d9ac-4724-44a2-98e8-7eb7bce86f23     datapack              0
4   714895d5-1e06-4159-861f-77973a3476b8     datapack          14287
..                                   ...          ...            ...
65  807ef283-b059-48b3-b90c-3f3f1dde2396       shader            836
66  8235114d-455f-4360-bb4d-dc5c73bc33ff       shader            836
67  8af5da09-b203-4d7e-bcab-e78002bb8f35       shader            836
68  9686352e-8206-416a-a615-74f4da8391aa       shader              0
69  bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e       shader              0

[70 rows x 3 columns]

In [19]:
with duckdb.connect(
    bronze_db_path,
    read_only=True,
) as con:
    print(
        con.execute(
            """
            SELECT
                run_id,
                project_type,
                status,
                end_time
            FROM main.ingestion_log
            ORDER BY end_time DESC
            LIMIT 20
            """
        ).df()
    )

                                  run_id           project_type   status  \
0   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e                 shader  success
1   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e           resourcepack  success
2   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e                 plugin  success
3   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e                modpack  success
4   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e                    mod  success
5   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e  minecraft_java_server  success
6   bc48ba6a-6ffc-49f8-92e5-6b276ff45a5e               datapack  success
7   8235114d-455f-4360-bb4d-dc5c73bc33ff  minecraft_java_server  success
8   8235114d-455f-4360-bb4d-dc5c73bc33ff               datapack  success
9   8235114d-455f-4360-bb4d-dc5c73bc33ff                 plugin  success
10  8235114d-455f-4360-bb4d-dc5c73bc33ff                 shader  success
11  8235114d-455f-4360-bb4d-dc5c73bc33ff           resourcepack  success
12  8235114d-455f-4360-bb4d-dc5c73bc33ff                modpack  success
13  8235114d-455f-4360-bb4d-dc5c73bc33ff                    mod  success
14  63a1d9ac-4724-44a2-98e8-7eb7bce86f23                 shader  success
15  63a1d9ac-4724-44a2-98e8-7eb7bce86f23           resourcepack  success
16  63a1d9ac-4724-44a2-98e8-7eb7bce86f23                 plugin  success
17  63a1d9ac-4724-44a2-98e8-7eb7bce86f23                modpack  success
18  63a1d9ac-4724-44a2-98e8-7eb7bce86f23                    mod  success
19  63a1d9ac-4724-44a2-98e8-7eb7bce86f23  minecraft_java_server  success

                           end_time
0  2026-08-26 16:22:07.506396-07:00
1  2026-08-26 16:19:48.401977-07:00
2  2026-08-26 14:07:16.548223-07:00
3  2026-08-26 13:01:05.068363-07:00
4  2026-08-26 11:51:48.274291-07:00
5  2026-08-26 07:08:04.025415-07:00
6  2026-08-26 07:01:07.130708-07:00
7  2026-08-26 06:03:35.860836-07:00
8  2026-08-26 06:03:34.544144-07:00
9  2026-08-26 06:03:22.591509-07:00
10 2026-08-26 06:02:03.920687-07:00
11 2026-08-26 06:02:03.152555-07:00
12 2026-08-26 06:01:05.577995-07:00
13 2026-08-26 06:00:44.381690-07:00
14 2026-08-26 05:55:05.963349-07:00
15 2026-08-26 05:51:48.407354-07:00
16 2026-08-26 03:42:20.816457-07:00
17 2026-08-26 02:34:24.896569-07:00
18 2026-08-26 01:24:46.466982-07:00
19 2026-08-25 20:41:51.012659-07:00

In [ ]:
def add_hashed_payload_to_bronze(
    bronze_db_path: str,
    table_name: str,
) -> None:
    with duckdb.connect(bronze_db_path) as bronze_con:
        columns = {
            row[1]
            for row in bronze_con.execute(
                f"PRAGMA table_info('{table_name}')"
            ).fetchall()
        }

        if "hashed_payload" not in columns:
            bronze_con.execute(
                f"""
                ALTER TABLE {table_name}
                ADD COLUMN hashed_payload VARCHAR;
                """
            )

        bronze_con.execute(
            f"""
            UPDATE {table_name}
            SET hashed_payload = md5(
                CAST(payload AS VARCHAR)
            )
            WHERE hashed_payload IS NULL;
            """
        )

        bronze_con.execute(
            f"""
            ALTER TABLE {table_name}
            ALTER COLUMN hashed_payload SET NOT NULL;
            """
        )

In [ ]:
def reorder_hashed_payload_column(
    bronze_db_path: str,
    table_name: str,
) -> None:
    temp_table_name = f"{table_name}_reordered"

    with duckdb.connect(bronze_db_path) as bronze_con:
        bronze_con.execute("BEGIN TRANSACTION")

        try:
            bronze_con.execute(
                f"""
                CREATE TABLE {temp_table_name} (
                    run_id VARCHAR NOT NULL,
                    project_type VARCHAR NOT NULL,
                    project_id VARCHAR NOT NULL,
                    payload JSON NOT NULL,
                    hashed_payload VARCHAR NOT NULL,
                    c_pull_timestamp_utc TIMESTAMPTZ NOT NULL,
                    PRIMARY KEY (
                        run_id,
                        project_type,
                        project_id
                    )
                );
                """
            )

            bronze_con.execute(
                f"""
                INSERT INTO {temp_table_name}
                (
                    run_id,
                    project_type,
                    project_id,
                    payload,
                    hashed_payload,
                    c_pull_timestamp_utc
                )
                SELECT
                    run_id,
                    project_type,
                    project_id,
                    payload,
                    hashed_payload,
                    c_pull_timestamp_utc
                FROM {table_name};
                """
            )

            bronze_con.execute(
                f"""
                DROP TABLE {table_name};
                """
            )

            bronze_con.execute(
                f"""
                ALTER TABLE {temp_table_name}
                RENAME TO {table_name};
                """
            )

            bronze_con.execute("COMMIT")

        except Exception:
            bronze_con.execute("ROLLBACK")
            raise

In [ ]:
reorder_hashed_payload_column(bronze_db_path="/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||api.modrinth.com.duckdb",
                              table_name='modrinth_project_listings')

In [ ]:
add_hashed_payload_to_bronze(bronze_db_path="/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||api.modrinth.com.duckdb",
                             table_name='modrinth_project_listings')

In [ ]:
with duckdb.connect("/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||piston-meta.mojang.com.duckdb") as con:
    df = con.execute("SELECT * FROM ingestion_log").fetch_df()
df

In [ ]:
with duckdb.connect("/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||api.modrinth.com.duckdb") as con:
    df = con.execute("SELECT * FROM ingestion_log").fetch_df()
df

In [ ]:
with duckdb.connect("/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/api.modrinth.com.duckdb") as con:
    df = con.execute("SELECT * FROM modrinth_project_listings LIMIT 10").fetch_df()
df

In [ ]:
duckdb.sql("SELECT version()").show()

In [ ]:
payload = json.loads(df["payload"].iloc[0])

print(
    json.dumps(
        payload,
        indent=4,
    )
)