In [24]:
import duckdb
import polars as pl
import pandas as pd
import json
import os
import numpy as np

In [58]:
from minecraft_data_dashboard.utils.db import (
    get_modrinth_overview_kpis,
    get_project_type_distribution,
    get_modrinth_project_listings_time_series,
    get_modrinth_overview_preview,
    get_mod_version_distribution,
    get_first_activity
)

In [25]:
modrinth_silver_path = "/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/silver/dev/api_modrinth_com.duckdb"
modrinth_bronze_path = "/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/api_modrinth_com.duckdb"
modrinth_gold_path = "/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/gold/dev/api_modrinth_com.duckdb"
mojang_version_manifest_db_path = "/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/silver/dev/piston_meta_mojang_com.duckdb"

In [56]:
with duckdb.connect(modrinth_silver_path) as silver_con:
    df_check = silver_con.execute('SELECT * FROM modrinth_project_versions LIMIT 100').fetch_df()
    
df_check

,run_id,project_type,project_id,version_id,hashed_payload,c_pull_timestamp_utc,author_id,name,version_number,changelog,...,dependencies,game_versions,version_type,loaders,featured,status,requested_status,date_published,downloads,files
0,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,1BZ68dI8,ol9uAtMf,fbc093a274364286d0caa3c34158aeff3f1a32c74d8588...,2026-08-26 05:51:48.540420-07:00,6NlRvOsq,Pegasus Vx (v0.3.3),0.3.3,None,...,[],"[1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2,...",alpha,[iris],False,listed,None,2025-08-14 11:07:59.542189-07:00,681,"[{""id"":""vGqgcdXD"",""hashes"":{""sha512"":""b6cb7ebb..."
1,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,1BZ68dI8,j6kmC96s,e167afeffd2be47bc0e3f651618f634523cf2f74264ac8...,2026-08-26 05:51:48.540420-07:00,6NlRvOsq,Pegasus (0.3.0b),0.3.0b,None,...,[],"[1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2,...",alpha,[iris],False,listed,None,2025-04-12 17:21:36.471812-07:00,2144,"[{""id"":""AnaA1hYA"",""hashes"":{""sha512"":""9094894e..."
2,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,1BZ68dI8,CrWpZCHu,4b6d21c3fb62019e93d9ad133492bd737bec394c4e43ba...,2026-08-26 05:51:48.540420-07:00,6NlRvOsq,Pegasus v_0.2.1,0.2.1,None,...,[],"[1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2,...",alpha,[iris],False,listed,None,2025-02-05 17:28:30.205182-08:00,23608,"[{""id"":""HEFrT6N9"",""hashes"":{""sha512"":""0d10a97c..."
3,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,1BZ68dI8,DvUxEAb6,fe9554d65946c7dd12f9ec9f1ea2e71caf2ca0973bcb60...,2026-08-26 05:51:48.540420-07:00,6NlRvOsq,Pegasus v0.2.0,0.2.0,None,...,[],"[1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1,...",alpha,[iris],False,listed,None,2025-02-05 13:43:34.074940-08:00,1562,"[{""id"":""foxF1XT7"",""hashes"":{""sha1"":""d38d5f651b..."
4,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,1BZ68dI8,7rY5E8Jp,875568f19f669fdfd97369bd103768c603f921447d582a...,2026-08-26 05:51:48.540420-07:00,6NlRvOsq,Pegasus Shaders v 0.1.2,0.1.2,None,...,[],"[1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2,...",beta,[iris],False,listed,None,2024-11-19 13:14:40.320452-08:00,18363,"[{""id"":""xYzQbjBt"",""hashes"":{""sha1"":""a6a156f658..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,A1wQqzrz,EzC8VCUP,0ce40eafc12c5e9eef240dd37f32b4b3d51250e05dc54b...,2026-08-26 05:52:53.441202-07:00,pXNNL5g4,The only version,1,None,...,[],[1.19.4],release,[vanilla],False,listed,None,2023-04-24 05:04:04.463518-07:00,1819,"[{""id"":""w4XfBj7b"",""hashes"":{""sha512"":""61e4e564..."
96,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,ARW1Jej5,Ru1EPCkc,000fa96c0e91e3d9350533893e46d6177d1ebacdae9497...,2026-08-26 05:52:52.082667-07:00,7U2MCbSd,Major fixes and improvements,1.1-beta,None,...,[],"[1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21....",beta,"[iris, optifine]",False,listed,None,2026-06-12 13:44:57.212719-07:00,220,"[{""id"":""LUEAqUlk"",""hashes"":{""sha512"":""a5ef0d34..."
97,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,ARW1Jej5,YuuwWKMW,1a422f644860decb371a09de478e9a3417808297d8532d...,2026-08-26 05:52:52.082667-07:00,7U2MCbSd,UNSTABLE,1.1-alpha,None,...,[],"[1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21....",alpha,"[iris, optifine]",False,listed,None,2026-06-11 16:15:14.443412-07:00,50,"[{""id"":""mElOnZYY"",""hashes"":{""sha1"":""75eb1bd356..."
98,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,ARW1Jej5,ghbDY2Wq,765621e17ceb517f75d25937a1c7d260beaae6c55901fd...,2026-08-26 05:52:52.082667-07:00,7U2MCbSd,First release of Polace,1.0-beta,None,...,[],"[1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21....",beta,"[iris, optifine]",False,listed,None,2026-06-10 14:31:53.051851-07:00,51,"[{""id"":""rYU525xY"",""hashes"":{""sha1"":""9751fa804c..."
99,63a1d9ac-4724-44a2-98e8-7eb7bce86f23,shader,Ah4Q0Hhi,F8HIL7tv,5db0336609f6cc20f1e2dee35e047a49f8039ee0d9f92c...,2026-08-26 05:52:52.639927-07:00,4Mek1Bg6,ASCII Shader V1.1,1.1,None,...,"[{""version_id"":null,""project_id"":""YL57xq9U"",""f...","[1.8.9, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.10,...",release,"[iris, optifine]",False,listed,None,2024-10-01 08:59:52.558008-07:00,660,"[{""id"":""8fkFpKpU"",""hashes"":{""sha512"":""723c3134..."

In [60]:
with duckdb.connect(modrinth_gold_path, read_only=True) as conn:
    tables = conn.execute(
        """
        SHOW TABLES
        """
    ).fetchall()

    for table_row in tables:
        table_name = table_row[0]

        print("=" * 100)
        print(f"TABLE: {table_name}")
        print("=" * 100)

        schema_df = conn.execute(
            f"""
            DESCRIBE {table_name}
            """
        ).df()

        print(schema_df.to_string(index=False))
        print()

====================================================================================================
TABLE: modrinth_project_signals
====================================================================================================
              column_name              column_type null  key default extra
               project_id                  VARCHAR  YES None    None  None
             project_type                  VARCHAR  YES None    None  None
                    title                  VARCHAR  YES None    None  None
           current_run_id                  VARCHAR  YES None    None  None
        comparison_run_id                  VARCHAR  YES None    None  None
          baseline_run_id                  VARCHAR  YES None    None  None
      current_observed_at TIMESTAMP WITH TIME ZONE  YES None    None  None
   comparison_observed_at TIMESTAMP WITH TIME ZONE  YES None    None  None
     baseline_observed_at TIMESTAMP WITH TIME ZONE  YES None    None  None
        current_downloads                   BIGINT  YES None    None  None
     comparison_downloads                   BIGINT  YES None    None  None
       baseline_downloads                   BIGINT  YES None    None  None
 current_downloads_gained                   BIGINT  YES None    None  None
baseline_downloads_gained                   BIGINT  YES None    None  None
            current_hours                   DOUBLE  YES None    None  None
           baseline_hours                   DOUBLE  YES None    None  None
         current_velocity                   DOUBLE  YES None    None  None
        baseline_velocity                   DOUBLE  YES None    None  None
            velocity_lift                   DOUBLE  YES None    None  None
           velocity_ratio                   DOUBLE  YES None    None  None
velocity_ratio_percentile                   DOUBLE  YES None    None  None
 download_gain_percentile                   DOUBLE  YES None    None  None
              trend_score                   DOUBLE  YES None    None  None
               trend_rank                   BIGINT  YES None    None  None
    is_trending_candidate                  BOOLEAN  YES None    None  None

====================================================================================================
TABLE: snapshot_api_project_listings
====================================================================================================
        column_name column_type null  key default extra
             run_id        UUID  YES None    None  None
       project_type     VARCHAR  YES None    None  None
         project_id     VARCHAR  YES None    None  None
               slug     VARCHAR  YES None    None  None
      display_title     VARCHAR  YES None    None  None
             author     VARCHAR  YES None    None  None
        description     VARCHAR  YES None    None  None
         categories   VARCHAR[]  YES None    None  None
   platform_loaders   VARCHAR[]  YES None    None  None
gameplay_categories   VARCHAR[]  YES None    None  None
           versions   VARCHAR[]  YES None    None  None
     latest_version     VARCHAR  YES None    None  None
     download_count      BIGINT  YES None    None  None
            follows      BIGINT  YES None    None  None
        client_side     VARCHAR  YES None    None  None
        server_side     VARCHAR  YES None    None  None
            license     VARCHAR  YES None    None  None
       date_created   TIMESTAMP  YES None    None  None
      date_modified   TIMESTAMP  YES None    None  None
  date_retrieved_at   TIMESTAMP  YES None    None  None

====================================================================================================
TABLE: snapshot_minecraft_java_versions
====================================================================================================
           column_name              column_type null  key default extra
                    id                  VARCHAR  YES None    None  None
                  type                  VARCHAR  YES None    None  None
                   url                  VARCHAR  YES None    None  None
                  time                  VARCHAR  YES None    None  None
           releaseTime                  VARCHAR  YES None    None  None
                  sha1                  VARCHAR  YES None    None  None
       complianceLevel                   BIGINT  YES None    None  None
     is_latest_release                  BOOLEAN  YES None    None  None
    is_latest_snapshot                  BOOLEAN  YES None    None  None
c_ingest_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

In [ ]:
with duckdb.connect(
    modrinth_gold_path,
    read_only=True,
) as conn:

    activity_df = conn.execute(
        f"""
       SELECT
    category_momentum_rank,
    gameplay_category,

    total_projects,
    momentum_project_count,

    ROUND(
        momentum_project_share * 100,
        2
    ) AS momentum_project_share_percent,

    projects_with_strong_discovery,
    projects_with_strong_activity,
    projects_with_breakout_signal,
    projects_with_strong_audience,

    total_downloads_gained,
    momentum_downloads_gained,

    ROUND(
        momentum_download_gain_share * 100,
        2
    ) AS momentum_download_gain_share_percent,

    ROUND(
        average_momentum_downloads_gained,
        2
    ) AS average_momentum_downloads_gained,

    ROUND(
        median_velocity_ratio,
        2
    ) AS median_velocity_ratio,

    ROUND(
        momentum_count_percentile * 100,
        2
    ) AS momentum_count_percentile,

    ROUND(
        momentum_share_percentile * 100,
        2
    ) AS momentum_share_percentile,

    ROUND(
        momentum_download_gain_share_percentile * 100,
        2
    ) AS momentum_demand_percentile,

    ROUND(
        category_momentum_score,
        2
    ) AS category_momentum_score

FROM modrinth_category_momentum_signals

WHERE project_type = 'mod'
    AND is_category_momentum_candidate = TRUE

ORDER BY
    category_momentum_rank

LIMIT 30;
        """
    ).df()

activity_df

,gameplay_category,category_momentum_rank,total_projects,momentum_project_count,title,current_downloads,current_downloads_gained,discovery_score,development_activity_score,content_opportunity_score,content_opportunity_rank
0,utility,1,35818,118,Just Enough Items (JEI),74544467,527732,NaN,99.470587,99.470587,1
1,utility,1,35818,118,Simple Voice Chat,66715071,511970,82.350276,96.255131,96.860868,2
2,utility,1,35818,118,Project: MCSR Ranked,1992041,40226,95.409014,89.344119,96.312155,5
3,utility,1,35818,118,Tensura EP Scaling,26558,7556,96.068735,NaN,96.068735,8
4,utility,1,35818,118,Quests & Teams Fixes,21744,7851,95.965438,48.918593,95.965438,10
...,...,...,...,...,...,...,...,...,...,...,...
215,worldgen,10,8265,14,The Broken Script,2862098,55199,NaN,80.017224,81.928013,175
216,worldgen,10,8265,14,MVS - Moog's Voyager Structures,7802533,77433,81.854378,NaN,81.854378,177
217,worldgen,10,8265,14,YUNG's API,33534348,165572,NaN,81.300131,81.300131,188
218,worldgen,10,8265,14,Wizards (RPG Series),5206890,22535,9.811565,80.886093,80.886093,196
219,worldgen,10,8265,14,Cobblemon: Mega Showdown,11794201,75102,49.794762,80.873927,80.873927,197

In [16]:
with duckdb.connect(modrinth_gold_path, read_only=True) as conn:
    activity_df = conn.execute("""
                               SELECT
    breakout_rank,
    project_id,
    title,

    current_downloads,
    comparison_downloads,
    current_downloads_gained,
    recent_growth_share,

    current_velocity,
    baseline_velocity,
    velocity_ratio,

    trend_rank,
    trend_score,

    trend_strength_percentile,
    underexposure_percentile,

    breakout_score

FROM modrinth_project_breakout_signals

WHERE is_breakout_candidate = TRUE

ORDER BY
    breakout_rank

LIMIT 30;""").df()
activity_df

,breakout_rank,project_id,title,current_downloads,comparison_downloads,current_downloads_gained,recent_growth_share,current_velocity,baseline_velocity,velocity_ratio,trend_rank,trend_score,trend_strength_percentile,underexposure_percentile,breakout_score
0,1,PsY5btQe,Potion API,24798,16727,8071,0.482513,125.096226,25.712723,4.865149,34,83.165222,0.977444,0.959672,96.847624
1,2,UJOmjHfx,Tensura: Ancient Artifacts,21822,14000,7822,0.558714,121.236858,63.191018,1.918577,45,81.745146,0.969925,0.963090,96.649509
2,3,9LFj5OCy,Tensura EP Scaling,26558,19002,7556,0.397642,117.113999,61.136072,1.915628,54,81.123665,0.963773,0.957621,96.068735
3,4,SWZGEk5x,Quests & Teams Fixes,21744,13893,7851,0.565105,121.686342,79.400337,1.532567,66,80.184014,0.955571,0.963773,95.965438
4,5,NysbPTkh,Legend of the Lucky Blocks,39189,27121,12068,0.444969,187.047609,39.855585,4.693134,15,88.747673,0.990431,0.926863,95.759282
5,6,PacPygzz,Hypixel Lucky Blocks,43907,33009,10898,0.330152,168.913229,33.454745,5.049007,16,87.278042,0.989747,0.916610,95.177544
6,7,PriJM6Wm,OPAC-UI,20560,13224,7336,0.554749,113.704115,75.745182,1.501140,97,78.692049,0.934381,0.967874,95.083297
7,8,k2XSGtXz,HE: HariEntity,12037,7121,4916,0.690352,76.195397,29.333342,2.597570,131,74.196055,0.911141,0.987013,94.756090
8,9,b0C4QetW,Stone Lucky Block,12125,7519,4606,0.612581,71.390561,13.124023,5.439686,136,73.568564,0.907724,0.986329,94.539554
9,10,KvsvCJwP,Christmas Lucky Block,32986,26722,6264,0.234414,97.088683,35.239152,2.755137,100,78.485302,0.932331,0.947368,93.978947
10,11,q38mmH7i,LDShadowLady's Disney Wish Rebrushed,19473,14843,4630,0.311932,71.762548,18.477242,3.883834,138,73.470838,0.906357,0.970608,93.738285
11,12,JWEYmR12,Pastek's Lucky Block,10494,6298,4196,0.666243,65.035778,10.746733,6.051679,160,72.079806,0.891319,0.988380,93.734369
12,13,IGRcH1wA,Rainbow Lucky Block,22109,17289,4820,0.278790,74.707447,16.583469,4.504935,130,74.245829,0.911825,0.961039,93.578538
13,14,s4WQHerM,3D Maps,6191,2417,3774,1.561440,58.495001,5.382001,10.868635,202,69.316659,0.862611,0.997266,92.506399
14,15,ROwCMI9N,Integrated Lucky Blocks,21559,17493,4066,0.232436,63.020847,10.821563,5.823637,172,71.416921,0.883117,0.964457,92.199624
15,16,IGVrnkhH,Create: Flight Control,19194,14974,4220,0.281822,65.407765,41.576674,1.573184,183,70.479415,0.875598,0.971975,92.127301
16,17,aMcWnMHI,Chat Block,55987,48472,7515,0.155038,116.478520,76.591336,1.520779,81,79.338780,0.945318,0.886535,91.498301
17,18,19P0GlZk,Enhanced Celestials 2: Default Lunar Events,13689,10480,3209,0.306202,49.737801,14.839355,3.351749,237,65.982888,0.838688,0.982912,90.509029
18,19,ZKBkklMv,MOS - Moog's Ocean Structures,10052,6831,3221,0.471527,49.923794,29.765053,1.677262,251,65.415494,0.829118,0.990431,90.262385
19,20,BngtDh26,ItemPhysic Lite Config,67796,60509,7287,0.120428,112.944641,72.884375,1.549641,90,78.956480,0.939166,0.860560,89.814669
20,21,UpkHNO8R,Screenshot Message Enhancer,80080,70024,10056,0.143608,155.862675,119.463143,1.304693,62,80.630323,0.958305,0.838688,89.451507
21,22,UQgc9Wcb,Upgrader items,28434,22802,5632,0.246996,87.293017,75.963915,1.149138,248,65.555431,0.831169,0.953520,88.815053
22,23,ugCWUHV9,Enhanced Celestials 2: Core,14675,11812,2863,0.242381,44.374984,17.418111,2.547635,284,63.046698,0.806562,0.980861,88.521321
23,24,j9jxyR07,Yahiraft,4601,1927,2674,1.387649,41.445584,5.658296,7.324747,314,61.576434,0.786056,0.999316,87.994942
24,25,7hJZhArg,SoundTweaks,84155,77271,6884,0.089089,106.698354,66.869198,1.595628,94,78.783132,0.936432,0.825701,87.758715
25,26,JyeqOA7R,FOVChanger,85847,78858,6989,0.088628,108.325799,68.244918,1.587309,91,78.850937,0.938483,0.820232,87.538211
26,27,2GLXmVz9,Remember My Txt,74514,69696,4818,0.069129,74.676449,46.970186,1.589869,149,72.811862,0.898838,0.848941,87.317701
27,28,4dNGXeZO,HyMod,63273,58979,4294,0.072806,66.554726,43.798548,1.519565,185,70.402466,0.874231,0.867396,87.079998
28,29,y0E9vcbS,Confirm Reset Keys,60975,56980,3995,0.070112,61.920384,38.790697,1.596269,198,69.413824,0.865345,0.874915,87.010356
29,30,onz2NN2n,Armor Model API,13531,10129,3402,0.335867,52.729198,44.143917,1.194484,323,61.216605,0.779904,0.983595,86.998628

In [15]:
with duckdb.connect(modrinth_gold_path, read_only=True) as conn:
    activity_df = conn.execute("""SELECT
    activity_rank,
    project_id,
    title,

    latest_version_number,
    latest_version_type,
    latest_release_at,
    days_since_latest_release,

    active_release_days_last_30_days,
    active_release_days_last_90_days,

    current_downloads_gained,
    current_velocity,

    release_recency_percentile,
    current_velocity_percentile,

    activity_score,
    trend_rank

FROM modrinth_project_activity_signals

WHERE is_activity_candidate = TRUE

ORDER BY
    activity_rank

LIMIT 30;""").df()
activity_df

,activity_rank,project_id,title,latest_version_number,latest_version_type,latest_release_at,days_since_latest_release,active_release_days_last_30_days,active_release_days_last_90_days,current_downloads_gained,current_velocity,release_recency_percentile,current_velocity_percentile,activity_score,trend_rank
0,1,u6dRKJwZ,Just Enough Items (JEI),30.26.0.186,beta,2026-08-26 11:40:51.326227-05:00,9.333333,15,54,527732,8179.566531,0.996473,0.992945,99.470587,<NA>
1,2,9eGKb6K1,Simple Voice Chat,fabric-2.6.22+26.3-snapshot-10,alpha,2026-08-25 12:36:08.884965-05:00,10.291667,4,20,511970,7935.263878,0.934744,0.992063,96.255131,41
2,3,c3onkd5k,AsyncParticles,20.1.4.0-alpha.2,alpha,2026-08-26 03:16:55.016274-05:00,9.666667,10,34,114138,1769.078556,0.976190,0.947972,96.187421,<NA>
3,4,P7dR8mSH,Fabric API,0.158.2+26.3,beta,2026-08-25 09:46:28.968740-05:00,10.416667,6,22,1921825,29787.269768,0.923280,1.000000,96.011004,282
4,5,5CTSrY8X,GPUBooster,1.3.2-1.21-1.21.1-neo,beta,2026-08-26 08:03:29.368206-05:00,9.458333,1,5,79122,1226.349100,0.986332,0.930335,95.751535,<NA>
5,6,VSNURh3q,Concurrent Chunk Management Engine (Fabric),0.4.2-alpha.0.65+26.3-snap-10,alpha,2026-08-25 10:54:15.052913-05:00,10.375000,7,40,274994,4262.261373,0.926808,0.982363,95.377722,93
6,7,rOUBggPv,SuperMartijn642's Core Lib,1.1.24a-neoforge-mc26.2,release,2026-08-25 18:46:55.444291-05:00,10.041667,7,11,99588,1543.561262,0.955467,0.938272,94.679142,<NA>
7,8,7MoE34WK,Gnetum,4.5.4+26.2-neoforge,release,2026-08-25 19:45:07.111887-05:00,10.000000,2,9,78988,1224.272171,0.960758,0.929453,94.484659,<NA>
8,9,Xy8aRQKS,Physics Mod,3.2.1,beta,2026-08-25 15:42:55.499271-05:00,10.166667,6,20,111751,1732.081321,0.944004,0.945326,94.466444,<NA>
9,10,WKwQAwke,LibJF,26.2.2+forge,beta,2026-08-25 08:14:14.636342-05:00,10.458333,2,4,159843,2477.481853,0.917549,0.966490,94.138372,<NA>
10,11,on1Y0osD,Verity JE,v6.0.0-beta.8,beta,2026-08-26 10:11:35.561114-05:00,9.375000,7,12,45788,709.689752,0.993386,0.888889,93.823690,<NA>
11,12,6iTJugQR,Amendments,1.21-2.1.9,release,2026-08-25 11:58:51.419741-05:00,10.333333,3,9,102072,1582.061946,0.930335,0.942681,93.646725,<NA>
12,13,TiF5QWZY,Respackopts,26.2.2,release,2026-08-25 09:58:00.534608-05:00,10.416667,1,3,103008,1596.569451,0.923280,0.943563,93.331134,<NA>
13,14,AtOSAunf,Optimized Block Entities [OBE],1.1.41-patch.2,release,2026-08-25 15:44:05.229390-05:00,10.166667,8,37,67042,1039.115497,0.944004,0.917989,93.081475,8
14,15,nmDcB62a,ModernFix,5.27.21+mc26.1.2,release,2026-08-24 16:22:10.401620-05:00,11.125000,4,12,357152,5535.666865,0.877866,0.987654,92.952955,<NA>
15,16,CYQ7VYrM,ToadLib,1.5.1-26.2-fabric,release,2026-08-26 07:54:24.874967-05:00,9.500000,1,2,40820,632.688383,0.982363,0.879189,92.791684,<NA>
16,17,4das1Fjq,Flashback,0.43.2,release,2026-08-25 01:21:37.655713-05:00,10.750000,3,5,120256,1863.904317,0.900794,0.955908,92.753295,<NA>
17,18,ufdDoWPd,Kiwi 🥝,26.0.18+fabric,release,2026-08-25 00:21:53.530590-05:00,10.791667,1,17,115334,1787.615923,0.895944,0.949735,92.205563,<NA>
18,19,JWGBpFUP,Create: Enchantment Industry,2.5.2-f,beta,2026-08-25 18:59:31.569971-05:00,10.041667,13,18,45897,711.379195,0.955467,0.889771,92.144954,<NA>
19,20,cuIIkdlx,KaleidoscopeChineseFood,1.1.10-neoforge+1.21.1,release,2026-08-26 01:16:50.609252-05:00,9.750000,3,12,39322,609.470176,0.970899,0.876543,92.131177,<NA>
20,21,byNkmv5G,SkyHanni for Hypixel SkyBlock,7.50.0,beta,2026-08-25 14:44:14.821359-05:00,10.208333,7,24,51842,803.523546,0.939153,0.900353,91.934387,46
21,22,4ZVIxU8x,Goety - The Dark Arts,2.5.57.2,release,2026-08-26 00:44:31.853021-05:00,9.791667,8,26,38553,597.551084,0.968695,0.873898,91.885775,<NA>
22,23,1oUDhxuy,Moog's Structure Lib (moogs_structures),3.1.2,alpha,2026-08-25 09:12:05.685544-05:00,10.416667,3,9,62341,966.252486,0.923280,0.914462,91.885009,<NA>
23,24,Aqlf1Shp,Forgified Fabric API,0.116.15+2.3.5+1.21.1,release,2026-08-24 14:25:12.025609-05:00,11.208333,6,25,199259,3088.408979,0.869048,0.974427,91.872530,<NA>
24,25,CllP7wW0,Smooth Scrolling,3.0.0-beta.1,beta,2026-08-25 05:47:04.225582-05:00,10.583333,3,4,62234,964.594043,0.910053,0.913580,91.181317,<NA>
25,26,tDRRddpZ,Only Bottle Caps,1.4.0-neoforge,release,2026-08-26 07:26:12.254545-05:00,9.500000,2,2,31013,480.685077,0.982363,0.845679,90.891116,<NA>
26,27,LWEC5GA8,WaypointsPlus,1.0.8,release,2026-08-25 16:26:15.198911-05:00,10.125000,4,7,37107,575.138849,0.947531,0.871252,90.779199,<NA>
27,28,fFEIiSDQ,Supplementaries,1.21.1-3.9.3,release,2026-08-24 10:35:55.311240-05:00,11.375000,4,15,158306,2453.659167,0.855379,0.965608,90.715759,<NA>
28,29,k23mNPhZ,Aquamirae,7.2.3,release,2026-08-24 20:41:53.551395-05:00,10.958333,5,12,61811,958.037767,0.888007,0.912698,90.018345,<NA>
29,30,I9W1u5Ac,Project: MCSR Ranked,5.8.17,release,2026-08-25 05:08:55.758092-05:00,10.583333,2,11,40226,623.481698,0.910053,0.877425,89.344119,1

In [ ]:
with duckdb.connect(modrinth_gold_path, read_only=True) as conn:
    fan_signals_df = conn.execute("""
                                  SELECT
    fan_affinity_rank,
    project_id,
    title,
    current_downloads,
    follows,
    follows_per_1000_downloads,
    follow_rate_percentile,
    follower_count_percentile,
    fan_affinity_score

FROM modrinth_project_fan_signals

WHERE is_fan_signal_candidate = TRUE

ORDER BY fan_affinity_rank;""").df()

In [6]:
fan_signals_df

,fan_affinity_rank,project_id,title,current_downloads,follows,follows_per_1000_downloads,follow_rate_percentile,follower_count_percentile,fan_affinity_score
0,1,74oZhrEe,The Roads More Travelled [TRMT],174517,1214,6.956342,0.982817,0.959255,97.089318
1,2,kjZCvAn6,No Man's Land,148668,1052,7.076170,0.983743,0.952104,96.766510
2,3,MGHiBUyJ,Etherology,23173,725,31.286411,1.000000,0.929725,96.358304
3,4,LtZfKhel,Simple Clouds,189662,1110,5.852517,0.971396,0.954574,96.291140
4,5,RQDFHc4w,Creatures and Beasts,36311,706,19.443144,0.999383,0.927873,96.230129
5,6,82nEyXEm,"The First City ($50,000 MrBeast Mod)",214649,1175,5.474053,0.966766,0.957506,96.211374
6,7,aT3Teaxa,Middle-earth,80677,718,8.899686,0.991974,0.929005,95.945770
7,8,ClzhCK3K,Fathoms,30991,623,20.102610,0.999486,0.917584,95.678532
8,9,Jjc1149h,RAT's Mischief,128726,791,6.144835,0.974997,0.936619,95.542296
9,10,a93H3mKU,Inspecio,117857,755,6.406068,0.977570,0.933326,95.493591
10,11,MNlxJdtO,Photonics: A raytracing engine,251985,1162,4.611386,0.949069,0.956940,95.298817
11,12,QsiPPta0,Tidal,90570,657,7.254058,0.984772,0.921494,95.208279
12,13,JD2NSu5O,The Aether II,63493,569,8.961618,0.992386,0.911462,95.020421
13,14,qvNFI0nc,Astronomical,67654,570,8.425222,0.990225,0.911668,94.932420
14,15,M5tLRhSi,Nekoma's Fixed,26151,507,19.387404,0.999280,0.899167,94.658347
15,16,DfvI9QGt,Defile,213762,943,4.411448,0.944027,0.946497,94.526025
16,17,1Bm99etE,Vibrancy (development paused),41028,501,12.211173,0.996913,0.897520,94.460943
17,18,Ty4YZsbO,PortalMod,32505,468,14.397785,0.998148,0.889906,94.092443
18,19,Jaoe8qGe,REPO Heads,142675,688,4.822148,0.954111,0.925507,93.959098
19,20,hEOCdOgW,Phosphor,857671,2840,3.311293,0.895668,0.985904,93.862235
20,21,rctNbbuL,Larion World Generation,160415,718,4.475891,0.945571,0.929005,93.721459
21,22,59ypHk8x,CliffTree,334301,1225,3.664362,0.914189,0.960078,93.657167
22,23,Hagcl1FT,NEEPMeat,59058,459,7.772021,0.988373,0.887128,93.501805
23,24,Jmx5kJiS,Cascades,174133,739,4.243883,0.938985,0.931063,93.500740
24,25,WP5prCOu,Sky Lands,92108,519,5.634690,0.969236,0.902356,93.460093
25,26,V3QHTHDA,DAP ur Homies!,91788,518,5.643439,0.969338,0.902048,93.448316
26,27,hd2YH2vf,Crop & Kettle,69629,473,6.793147,0.981068,0.890987,93.386006
27,28,zJIYJfn8,Catenary,68278,467,6.839685,0.981480,0.889701,93.333926
28,29,Ic0nDh2h,Places,85099,499,5.863759,0.971499,0.896852,93.268410
29,30,6kq7BzRK,Mod Manager,13565,410,30.224843,0.999897,0.873650,93.251978

In [62]:
with duckdb.connect(modrinth_gold_path, read_only=True) as conn:
    signals_df = conn.execute("""SELECT
    trend_rank,
    project_id,
    title,
    current_downloads,
    current_downloads_gained,
    current_velocity,
    baseline_velocity,
    velocity_lift,
    velocity_ratio,
    velocity_ratio_percentile,
    download_gain_percentile,
    trend_score

FROM modrinth_project_signals

WHERE is_trending_candidate = TRUE

ORDER BY trend_rank

LIMIT 30;""").df()
signals_df

,trend_rank,project_id,title,current_downloads,current_downloads_gained,current_velocity,baseline_velocity,velocity_lift,velocity_ratio,velocity_ratio_percentile,download_gain_percentile,trend_score
0,1,I9W1u5Ac,Project: MCSR Ranked,1992041,40226,623.481698,264.138224,359.343473,2.360437,0.975393,0.933698,95.409014
1,2,AibBIVmj,OneConfig,557197,34610,536.436672,193.481480,342.955192,2.772548,0.981545,0.917293,94.833195
2,3,y6DuFGwJ,Skyblocker • Hypixel Skyblock,4566123,63682,987.037276,633.280142,353.757134,1.558611,0.930964,0.959672,94.509988
3,4,jJJLywXp,Odin - Hypixel Skyblock,1427513,34786,539.164579,306.273244,232.891334,1.760404,0.962406,0.918660,94.002448
4,5,IMuO8COj,[ESF] Entity Sound Features,2567675,28437,440.758441,236.197871,204.560570,1.866056,0.967874,0.904990,93.537626
5,6,fB1gJLGX,e4all,153369,23316,361.385653,89.582967,271.802686,4.034089,0.990431,0.884484,93.446389
6,7,UR0ocuEt,NBT Autocomplete,1400184,28400,440.184960,250.001119,190.183841,1.760732,0.963090,0.904306,93.277267
7,8,AtOSAunf,Optimized Block Entities [OBE],1011781,67042,1039.115497,761.958882,277.156615,1.363742,0.889952,0.961039,92.413052
8,9,eHe8QhtD,Compose Multiplatform,144741,17616,273.038671,91.436447,181.602224,2.986103,0.983595,0.858510,91.680576
9,10,2Uev7LdA,LambdaBetterGrass,1650706,18272,283.206324,166.830504,116.375820,1.697569,0.958988,0.863295,90.862890
10,11,Br0kXPwc,Tensura: Reincarnated,1465376,15210,235.746945,126.623794,109.123151,1.861790,0.967191,0.838004,89.797486
11,12,6avVoBVB,Simply Tooltips,384577,25635,397.328925,282.414002,114.914923,1.406902,0.899522,0.896104,89.780946
12,13,wRRSWpd1,ManasCore,1239824,19007,294.598435,197.211465,97.386970,1.493820,0.915926,0.867396,89.100063
13,14,bjvFzLV3,Tensura: Mysticism,1043681,16045,248.689003,157.753055,90.935948,1.576445,0.937116,0.844156,88.821002
14,15,NysbPTkh,Legend of the Lucky Blocks,39189,12068,187.047609,39.855585,147.192025,4.693134,0.993165,0.802119,88.747673
15,16,PacPygzz,Hypixel Lucky Blocks,43907,10898,168.913229,33.454745,135.458483,5.049007,0.995215,0.777170,87.278042
16,17,zy0karK1,Animatium,578509,14758,228.741185,155.617523,73.123662,1.469893,0.909091,0.835270,87.061841
17,18,1aD7nY4F,Tensura: Better Subordinates,319143,11972,185.559660,111.525412,74.034248,1.663833,0.954887,0.799727,87.044647
18,19,PcmQvtAt,Tensura: SlimeThrone Extras,630551,16883,261.677559,192.197858,69.479701,1.361501,0.887218,0.850991,86.872707
19,20,oLS8HdJ1,Streams Reflowing,174094,16557,256.624732,188.462117,68.162615,1.361678,0.887902,0.847573,86.726896
20,21,8pJYUDNi,Chatting,1677633,13882,215.163649,150.442744,64.720905,1.430203,0.903623,0.826384,86.327921
21,22,P1OZGk5p,ViaVersion,2907830,28456,441.052931,352.552693,88.500238,1.251027,0.823650,0.905673,86.271644
22,23,N6n5dqoA,Axiom,12519968,119767,1856.325076,1548.968530,307.356546,1.198427,0.767601,0.980861,86.122531
23,24,Kw7Sm3Xf,Noxesium,8302058,24479,379.411537,303.003751,76.407786,1.252168,0.824334,0.891319,85.651870
24,25,xUTHly0N,Centered Crosshair,1600036,14316,221.890419,167.550023,54.340396,1.324323,0.873548,0.829118,85.075321
25,26,ODKaullJ,Tensura: Not Enough Bosses,678908,11131,172.524605,112.135564,60.389042,1.538536,0.925496,0.781271,84.728989
26,27,NpvuJQoq,ViaBackwards,1955936,18990,294.334944,235.484108,58.850835,1.249914,0.821599,0.866712,84.355312
27,28,8aoMKplv,Punchy!,4262447,112686,1746.573325,1491.930837,254.642489,1.170680,0.729323,0.980178,83.634516
28,29,bFBJU91s,MouseTweaks x Accessories Fix,450630,15887,246.240087,196.135065,50.105022,1.255462,0.826384,0.843472,83.484080
29,30,h1E7sQNL,Customizable Player Models,2892383,17699,274.325127,221.456370,52.868757,1.238732,0.809979,0.859877,83.418273

In [8]:
import duckdb

modrinth_silver_path = (
    "/Users/admin/AroTekCodingSpace/Python-Workspace/"
    "Minecraft-Data-Platform/data/silver/dev/api_modrinth_com.duckdb"
)

with duckdb.connect(modrinth_silver_path, read_only=True) as conn:
    tables = conn.execute(
        """
        SHOW TABLES
        """
    ).fetchall()

    for table_row in tables:
        table_name = table_row[0]

        print("=" * 100)
        print(f"TABLE: {table_name}")
        print("=" * 100)

        schema_df = conn.execute(
            f"""
            DESCRIBE {table_name}
            """
        ).df()

        print(schema_df.to_string(index=False))
        print()

====================================================================================================
TABLE: modrinth_categories
====================================================================================================
         column_name              column_type null  key default extra
              header                  VARCHAR  YES None    None  None
                icon                  VARCHAR  YES None    None  None
                name                  VARCHAR  YES None    None  None
        project_type                  VARCHAR  YES None    None  None
              run_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

====================================================================================================
TABLE: modrinth_game_versions
====================================================================================================
         column_name              column_type null  key default extra
                date                  VARCHAR  YES None    None  None
               major                  BOOLEAN  YES None    None  None
             version                  VARCHAR  YES None    None  None
        version_type                  VARCHAR  YES None    None  None
              run_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

====================================================================================================
TABLE: modrinth_loaders
====================================================================================================
            column_name              column_type null  key default extra
                   icon                  VARCHAR  YES None    None  None
                   name                  VARCHAR  YES None    None  None
supported_project_types                VARCHAR[]  YES None    None  None
                 run_id                  VARCHAR  YES None    None  None
         hashed_payload                  VARCHAR  YES None    None  None
   c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

====================================================================================================
TABLE: modrinth_project_listings
====================================================================================================
         column_name              column_type null  key default extra
              run_id                  VARCHAR  YES None    None  None
        project_type                  VARCHAR  YES None    None  None
          project_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None
   all_project_types                VARCHAR[]  YES None    None  None
              author                  VARCHAR  YES None    None  None
           author_id                  VARCHAR  YES None    None  None
          categories                VARCHAR[]  YES None    None  None
         client_side                  VARCHAR  YES None    None  None
               color                   BIGINT  YES None    None  None
        date_created                  VARCHAR  YES None    None  None
       date_modified                  VARCHAR  YES None    None  None
         description                  VARCHAR  YES None    None  None
    disclosure_types                VARCHAR[]  YES None    None  None
  display_categories                VARCHAR[]  YES None    None  None
           downloads                   BIGINT  YES None    None  None
         environment                VARCHAR[]  YES None    None  None
    featured_gallery                  VARCHAR  YES None    None  None
             follows                   BIGINT  YES None    None  None
             gallery                VARCHAR[]  YES None    None  None
            icon_url                  VARCHAR  YES None    None  None
      latest_version                  VARCHAR  YES None    None  None
             license                  VARCHAR  YES None    None  None
        organization                  VARCHAR  YES None    None  None
     organization_id                  VARCHAR  YES None    None  None
         server_side                  VARCHAR  YES None    None  None
                slug                  VARCHAR  YES None    None  None
               title                  VARCHAR  YES None    None  None
            versions                VARCHAR[]  YES None    None  None

====================================================================================================
TABLE: modrinth_project_listings__dbt_tmp20260902012309187968
====================================================================================================
         column_name              column_type null  key default extra
              run_id                  VARCHAR  YES None    None  None
        project_type                  VARCHAR  YES None    None  None
          project_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None
   all_project_types                VARCHAR[]  YES None    None  None
              author                  VARCHAR  YES None    None  None
           author_id                  VARCHAR  YES None    None  None
          categories                VARCHAR[]  YES None    None  None
         client_side                  VARCHAR  YES None    None  None
               color                   BIGINT  YES None    None  None
        date_created                  VARCHAR  YES None    None  None
       date_modified                  VARCHAR  YES None    None  None
         description                  VARCHAR  YES None    None  None
    disclosure_types                VARCHAR[]  YES None    None  None
  display_categories                VARCHAR[]  YES None    None  None
           downloads                   BIGINT  YES None    None  None
         environment                VARCHAR[]  YES None    None  None
    featured_gallery                  VARCHAR  YES None    None  None
             follows                   BIGINT  YES None    None  None
             gallery                VARCHAR[]  YES None    None  None
            icon_url                  VARCHAR  YES None    None  None
      latest_version                  VARCHAR  YES None    None  None
             license                  VARCHAR  YES None    None  None
        organization                  VARCHAR  YES None    None  None
     organization_id                  VARCHAR  YES None    None  None
         server_side                  VARCHAR  YES None    None  None
                slug                  VARCHAR  YES None    None  None
               title                  VARCHAR  YES None    None  None
            versions                VARCHAR[]  YES None    None  None

====================================================================================================
TABLE: modrinth_project_types
====================================================================================================
         column_name              column_type null  key default extra
        project_type                  VARCHAR  YES None    None  None
              run_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

====================================================================================================
TABLE: modrinth_project_versions
====================================================================================================
         column_name              column_type null  key default extra
              run_id                  VARCHAR  YES None    None  None
        project_type                  VARCHAR  YES None    None  None
          project_id                  VARCHAR  YES None    None  None
          version_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None
           author_id                  VARCHAR  YES None    None  None
                name                  VARCHAR  YES None    None  None
      version_number                  VARCHAR  YES None    None  None
           changelog                  VARCHAR  YES None    None  None
       changelog_url                  VARCHAR  YES None    None  None
        dependencies                     JSON  YES None    None  None
       game_versions                VARCHAR[]  YES None    None  None
        version_type                  VARCHAR  YES None    None  None
             loaders                VARCHAR[]  YES None    None  None
            featured                  BOOLEAN  YES None    None  None
              status                  VARCHAR  YES None    None  None
    requested_status                  VARCHAR  YES None    None  None
      date_published TIMESTAMP WITH TIME ZONE  YES None    None  None
           downloads                   BIGINT  YES None    None  None
               files                     JSON  YES None    None  None

====================================================================================================
TABLE: modrinth_statistics
====================================================================================================
         column_name              column_type null  key default extra
             authors                   BIGINT  YES None    None  None
               files                   BIGINT  YES None    None  None
            projects                   BIGINT  YES None    None  None
            versions                   BIGINT  YES None    None  None
              run_id                  VARCHAR  YES None    None  None
      hashed_payload                  VARCHAR  YES None    None  None
c_pull_timestamp_utc TIMESTAMP WITH TIME ZONE  YES None    None  None

### Trend detection

In [26]:
project_download_metrics_query = """
    WITH run_summary AS (
        SELECT
            run_id,
            MAX(c_pull_timestamp_utc) AS observed_at

        FROM modrinth_project_listings

        WHERE project_type = 'mod'

        GROUP BY
            run_id
    ),

    ranked_runs AS (
        SELECT
            run_id,
            observed_at,

            ROW_NUMBER() OVER (
                ORDER BY
                    observed_at DESC,
                    run_id DESC
            ) AS run_rank

        FROM run_summary
    ),

    selected_runs AS (
        SELECT
            run_id,
            observed_at,
            run_rank

        FROM ranked_runs

        WHERE run_rank <= 30
    ),

    project_snapshots AS (
        SELECT
            p.run_id,
            r.run_rank,
            r.observed_at,

            p.project_id,

            JSON_EXTRACT_STRING(
                p.payload,
                '$.title'
            ) AS title,

            TRY_CAST(
                JSON_EXTRACT_STRING(
                    p.payload,
                    '$.downloads'
                )
                AS BIGINT
            ) AS total_downloads,

            p.c_pull_timestamp_utc,

            ROW_NUMBER() OVER (
                PARTITION BY
                    p.run_id,
                    p.project_id

                ORDER BY
                    p.c_pull_timestamp_utc DESC
            ) AS row_num

        FROM modrinth_project_listings AS p

        INNER JOIN selected_runs AS r
            ON p.run_id = r.run_id

        WHERE p.project_type = 'mod'
    ),

    deduped_snapshots AS (
        SELECT
            run_id,
            run_rank,
            observed_at,
            project_id,
            title,
            total_downloads

        FROM project_snapshots

        WHERE row_num = 1
    ),

    with_previous AS (
        SELECT
            *,

            LAG(run_id) OVER (
                PARTITION BY project_id
                ORDER BY observed_at
            ) AS previous_run_id,

            LAG(total_downloads) OVER (
                PARTITION BY project_id
                ORDER BY observed_at
            ) AS previous_total_downloads,

            LAG(observed_at) OVER (
                PARTITION BY project_id
                ORDER BY observed_at
            ) AS previous_observed_at

        FROM deduped_snapshots
    ),

    interval_metrics AS (
        SELECT
            *,

            total_downloads
                - previous_total_downloads
                AS downloads_gained,

            DATE_DIFF(
                'second',
                previous_observed_at,
                observed_at
            ) / 3600.0
                AS hours_since_previous_snapshot

        FROM with_previous
    )

    SELECT
        run_id,
        run_rank,
        observed_at,

        project_id,
        title,

        total_downloads,
        previous_total_downloads,
        downloads_gained,

        hours_since_previous_snapshot,

        downloads_gained
            / NULLIF(
                hours_since_previous_snapshot,
                0
            ) AS download_velocity

    FROM interval_metrics

    WHERE previous_total_downloads IS NOT NULL

    ORDER BY
        observed_at DESC,
        download_velocity DESC
"""

with duckdb.connect(modrinth_bronze_path, read_only=True) as bronze_con:
    df = bronze_con.execute(project_download_metrics_query).fetch_df()
    
df.head(25)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,run_id,run_rank,observed_at,project_id,title,total_downloads,previous_total_downloads,downloads_gained,hours_since_previous_snapshot,download_velocity
0,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,P7dR8mSH,Fabric API,247786665,245864840,1921825,64.518333,29787.269768
1,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,AANobbMI,Sodium,220091956,218493006,1598950,64.518333,24782.878252
2,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,NNAgCjsB,Entity Culling,161859058,160655791,1203267,64.518333,18650.001292
3,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,YL57xq9U,Iris Shaders,171285854,170092881,1192973,64.518333,18490.449743
4,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,9s6osm5g,Cloth Config API,163416736,162414763,1001973,64.518333,15530.050890
5,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,OhduvhIc,VeinMiner,79381136,78434372,946764,64.518333,14674.340627
6,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,uXXizFIs,FerriteCore,147035646,146173009,862637,64.518333,13370.416677
7,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,mOgUt4GM,Mod Menu,140006599,139176104,830495,64.518333,12872.232699
8,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,dxa0Bm8m,VeinMiner Hotkey,54269255,53438919,830336,64.518333,12869.768283
9,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,Ha28R6CL,Fabric Language Kotlin,114545146,113735351,809795,64.518333,12551.393661
10,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,1eAoo2KR,YetAnotherConfigLib (YACL),119039711,118278603,761108,64.518333,11796.770944
11,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,5ZwdcRci,ImmediatelyFast,120234559,119516428,718131,64.518333,11130.650203
12,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,gvQqBUqZ,Lithium,124468972,123753483,715489,64.518333,11089.700602
13,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,1bokaNcj,Xaero's Minimap,107184393,106573729,610664,64.518333,9464.968614
14,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,4I1XuqiY,[EMF] Entity Model Features,93089148,92502068,587080,64.518333,9099.429103
15,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,BVzZfTc1,[ETF] Entity Texture Features,98148479,97569804,578675,64.518333,8969.156054
16,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,NcUtCpym,Xaero's World Map,93838130,93304673,533457,64.518333,8268.301000
17,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,PtjYWJkn,Sodium Extra,93636153,93105632,530521,64.518333,8222.794555
18,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,u6dRKJwZ,Just Enough Items (JEI),74544467,74016735,527732,64.518333,8179.566531
19,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,eXts2L7r,Text Placeholder API,62057965,61542249,515716,64.518333,7993.324895
20,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,EsAfCjCV,AppleSkin,86899263,86386879,512384,64.518333,7941.680659
21,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,9eGKb6K1,Simple Voice Chat,66715071,66203101,511970,64.518333,7935.263878
22,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,lhGA9TYQ,Architectury API,97069176,96568100,501076,64.518333,7766.412648
23,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,zV5r3pPn,3D Skin Layers,74249447,73749693,499754,64.518333,7745.922348
24,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,MPCX6s5C,Not Enough Animations,84036735,83542067,494668,64.518333,7667.092041

In [27]:
project_download_metrics_df = (
    df
    .sort_values(
        [
            "project_id",
            "observed_at",
        ]
    )
    .copy()
)

In [28]:
project_download_metrics_df["previous_velocity"] = (
    project_download_metrics_df
    .groupby("project_id")["download_velocity"]
    .shift(1)
)

In [29]:
project_download_metrics_df["baseline_velocity"] = (
    project_download_metrics_df
    .groupby("project_id")["download_velocity"]
    .transform(
        lambda series: (
            series
            .shift(1)
            .rolling(
                window=7,
                min_periods=3,
            )
            .median()
        )
    )
)

In [30]:
project_download_metrics_df["velocity_ratio"] = np.where(
    project_download_metrics_df["baseline_velocity"] > 0,
    (
        project_download_metrics_df["download_velocity"]
        / project_download_metrics_df["baseline_velocity"]
    ),
    np.nan,
)

project_download_metrics_df["acceleration"] = np.where(
    project_download_metrics_df["previous_velocity"] > 0,
    (
        project_download_metrics_df["download_velocity"]
        / project_download_metrics_df["previous_velocity"]
    ),
    np.nan,
)

In [31]:
latest_observed_at = (
    project_download_metrics_df["observed_at"].max()
)

latest_trend_metrics_df = (
    project_download_metrics_df[
        project_download_metrics_df["observed_at"]
        == latest_observed_at
    ]
    .copy()
)

In [32]:
latest_trend_metrics_df = (
    latest_trend_metrics_df[
        latest_trend_metrics_df["baseline_velocity"].notna()
    ]
)

In [33]:
trending_mods_df = (
    latest_trend_metrics_df
    .sort_values(
        "velocity_ratio",
        ascending=False,
    )
)

In [34]:
trending_mods_df[
    [
        "project_id",
        "title",
        "total_downloads",
        "downloads_gained",
        "download_velocity",
        "previous_velocity",
        "baseline_velocity",
        "velocity_ratio",
        "acceleration",
    ]
].head(30)

,project_id,title,total_downloads,downloads_gained,download_velocity,previous_velocity,baseline_velocity,velocity_ratio,acceleration
3416,SIG65WOL,MaceBot,80375,1877,29.092506,0.0,0.819579,35.496898,NaN
22115,8L2Wendd,afkmon,76,38,0.588980,0.0,0.049047,12.008543,NaN
19188,2grfsR75,AdvancedPlayTime [1.21 - 1.26],3286,50,0.774974,0.0,0.070236,11.033901,NaN
19341,681HeTaF,Colored Bricks Mod,4944,49,0.759474,0.0,0.070236,10.813223,NaN
17356,8XUM9Lwf,Flint Required,3651,62,0.960967,0.0,0.095980,10.012210,NaN
19433,Vw4gxpH7,Spell Powered Weapons,128,49,0.759474,0.0,0.095509,7.951862,NaN
9986,gE1dmuDj,Sculk And Jaw,2325,200,3.099894,0.0,0.458453,6.761644,NaN
9065,gXy6YNys,Nourished,2960,245,3.797370,0.0,0.575877,6.594063,NaN
9342,F5ao3BYo,Crystals Overhauled,35622,230,3.564878,0.0,0.584226,6.101883,NaN
34209,fBT7OYMU,NPC Mod,36,18,0.278990,0.0,0.045981,6.067474,NaN
14555,KMnOsM3N,GregTech Modern Utilities,9752,88,1.363953,0.0,0.229226,5.950247,NaN
464,I9W1u5Ac,Project: MCSR Ranked,1992041,40226,623.481698,0.0,108.865304,5.727093,NaN
20852,8TVKynTx,Celestial Adventure,148,43,0.666477,0.0,0.140471,4.744577,NaN
21182,L0etlzzl,EmeraldCraft,1040,41,0.635478,0.0,0.140471,4.523899,NaN
16726,Rtw99Org,360 FOV,664,66,1.022965,0.0,0.229226,4.462685,NaN
32879,BZmT2pkS,Better Brewings,194,20,0.309989,0.0,0.070236,4.413560,NaN
160,Xy8aRQKS,Physics Mod,22732430,111751,1732.081321,0.0,402.531646,4.302969,NaN
18529,p03qyoEL,Custom Gateways,140,54,0.836971,0.0,0.202318,4.136914,NaN
2628,5vV6tCDu,钠-汉化模组（Sodium Chinese Localization Mod）,360244,3421,53.023688,0.0,13.631938,3.889666,NaN
12743,AVcrY8zI,Brick Variety,16567,118,1.828938,0.0,0.479898,3.811099,NaN
4368,xtym7fz7,SodiumLeafCulling-Unofficial,20711,1144,17.731394,0.0,4.894956,3.622381,NaN
40395,3ql7OHjb,Asset Bridge,27,10,0.154995,0.0,0.042916,3.611592,NaN
2237,ofdM7yJE,Ecliptic Seasons,318272,4735,73.389993,0.0,20.539618,3.573094,NaN
19589,SiezABuM,Quacked SMP - Server Management Panel,1169,48,0.743975,0.0,0.210707,3.530848,NaN
22518,VMRWxo2A,Aetherial Structure Compatibility,102,37,0.573480,0.0,0.162467,3.529820,NaN
1612,1A2XNzUB,Progress Peek,309831,8606,133.388443,0.0,39.255625,3.397945,NaN
12607,tUvv9kNQ,Better Furnaces,2391,121,1.875436,0.0,0.561885,3.337755,NaN
21245,fm6gX6MR,Integrated Mining,247,41,0.635478,0.0,0.191959,3.310489,NaN
14160,iwvovClp,Igrium's Replay Exporter,22927,94,1.456950,0.0,0.458453,3.177973,NaN
8797,bR35WQGQ,NarrativeCraft,8003,263,4.076361,0.0,1.343713,3.033654,NaN

In [35]:
breakout_mods_df = (
    latest_trend_metrics_df[
        (latest_trend_metrics_df["baseline_velocity"] <= 0)
        & (latest_trend_metrics_df["downloads_gained"] >= 1_000)
    ]
    .sort_values(
        "downloads_gained",
        ascending=False,
    )
)

In [36]:
breakout_mods_df[
    [
        "project_id",
        "title",
        "total_downloads",
        "downloads_gained",
        "download_velocity",
        "previous_velocity",
        "baseline_velocity",
    ]
].head(30)

,project_id,title,total_downloads,downloads_gained,download_velocity,previous_velocity,baseline_velocity
1,AANobbMI,Sodium,220091956,1598950,24782.878252,0.0,0.0
2,NNAgCjsB,Entity Culling,161859058,1203267,18650.001292,0.0,0.0
3,YL57xq9U,Iris Shaders,171285854,1192973,18490.449743,0.0,0.0
4,9s6osm5g,Cloth Config API,163416736,1001973,15530.050890,0.0,0.0
5,OhduvhIc,VeinMiner,79381136,946764,14674.340627,0.0,0.0
6,uXXizFIs,FerriteCore,147035646,862637,13370.416677,0.0,0.0
7,mOgUt4GM,Mod Menu,140006599,830495,12872.232699,0.0,0.0
8,dxa0Bm8m,VeinMiner Hotkey,54269255,830336,12869.768283,0.0,0.0
9,Ha28R6CL,Fabric Language Kotlin,114545146,809795,12551.393661,0.0,0.0
10,1eAoo2KR,YetAnotherConfigLib (YACL),119039711,761108,11796.770944,0.0,0.0
11,5ZwdcRci,ImmediatelyFast,120234559,718131,11130.650203,0.0,0.0
12,gvQqBUqZ,Lithium,124468972,715489,11089.700602,0.0,0.0
13,1bokaNcj,Xaero's Minimap,107184393,610664,9464.968614,0.0,0.0
14,4I1XuqiY,[EMF] Entity Model Features,93089148,587080,9099.429103,0.0,0.0
15,BVzZfTc1,[ETF] Entity Texture Features,98148479,578675,8969.156054,0.0,0.0
16,NcUtCpym,Xaero's World Map,93838130,533457,8268.301000,0.0,0.0
17,PtjYWJkn,Sodium Extra,93636153,530521,8222.794555,0.0,0.0
19,eXts2L7r,Text Placeholder API,62057965,515716,7993.324895,0.0,0.0
20,EsAfCjCV,AppleSkin,86899263,512384,7941.680659,0.0,0.0
22,lhGA9TYQ,Architectury API,97069176,501076,7766.412648,0.0,0.0
23,zV5r3pPn,3D Skin Layers,74249447,499754,7745.922348,0.0,0.0
24,MPCX6s5C,Not Enough Animations,84036735,494668,7667.092041,0.0,0.0
25,Bh37bMuy,Reese's Sodium Options,78459806,431627,6689.989925,0.0,0.0
26,8BmcQJ2H,Geckolib,67428661,428134,6635.850275,0.0,0.0
27,yBW8D80W,LambDynamicLights - Dynamic Lights,55618477,403810,6258.841156,0.0,0.0
28,51shyZVL,More Culling,63678940,395179,6125.065227,0.0,0.0
29,1IjD5062,Continuity,71153089,385239,5971.000491,0.0,0.0
30,Wq5SjeWM,FancyMenu,63456286,374479,5804.226189,0.0,0.0
31,w7ThoJFB,Zoomify (Zoom),64157350,369381,5725.209889,0.0,0.0
32,ordsPcFz,Kotlin for Forge,48513915,364062,5642.768205,0.0,0.0

In [37]:
projects_to_inspect = [
    "AANobbMI",  # Sodium
    "SIG65WOL",  # MaceBot
    "I9W1u5Ac",  # Project: MCSR Ranked
    "Xy8aRQKS",  # Physics Mod
]

project_history_df = (
    project_download_metrics_df[
        project_download_metrics_df["project_id"].isin(
            projects_to_inspect
        )
    ]
    [
        [
            "project_id",
            "title",
            "observed_at",
            "total_downloads",
            "previous_total_downloads",
            "downloads_gained",
            "hours_since_previous_snapshot",
            "download_velocity",
            "previous_velocity",
            "baseline_velocity",
            "velocity_ratio",
        ]
    ]
    .sort_values(
        [
            "project_id",
            "observed_at",
        ]
    )
)

project_history_df

,project_id,title,observed_at,total_downloads,previous_total_downloads,downloads_gained,hours_since_previous_snapshot,download_velocity,previous_velocity,baseline_velocity,velocity_ratio
812223,AANobbMI,Sodium,2026-08-21 18:49:04.682461-07:00,211656843,211008015,648828,1.749722,370817.717098,NaN,NaN,NaN
742650,AANobbMI,Sodium,2026-08-21 18:56:59.493730-07:00,211656843,211656843,0,0.131944,0.000000,370817.717098,NaN,NaN
669852,AANobbMI,Sodium,2026-08-21 19:07:50.310225-07:00,211656843,211656843,0,0.180833,0.000000,0.000000,NaN,NaN
594168,AANobbMI,Sodium,2026-08-24 17:25:04.729335-07:00,213698656,211656843,2041813,70.287222,29049.561719,0.000000,0.000000,NaN
524352,AANobbMI,Sodium,2026-08-24 21:46:49.053741-07:00,213698656,213698656,0,4.362500,0.000000,29049.561719,14524.780859,0.000000
451132,AANobbMI,Sodium,2026-08-25 00:13:14.438090-07:00,213698656,213698656,0,2.440278,0.000000,0.000000,0.000000,NaN
378331,AANobbMI,Sodium,2026-08-25 14:27:30.458835-07:00,213698656,213698656,0,14.237778,0.000000,0.000000,0.000000,NaN
301496,AANobbMI,Sodium,2026-08-25 19:35:36.229194-07:00,214315937,213698656,617281,5.135000,120210.516066,0.000000,0.000000,NaN
231723,AANobbMI,Sodium,2026-08-26 06:00:44.010241-07:00,214315937,214315937,0,10.418889,0.000000,120210.516066,0.000000,NaN
221255,AANobbMI,Sodium,2026-08-27 21:11:46.071527-07:00,215469572,214315937,1153635,39.183889,29441.564702,0.000000,0.000000,NaN
148091,AANobbMI,Sodium,2026-09-02 01:07:19.439631-07:00,218493006,215469572,3023434,123.925833,24397.124624,29441.564702,0.000000,NaN
80947,AANobbMI,Sodium,2026-09-02 01:19:14.161295-07:00,218493006,218493006,0,0.198611,0.000000,24397.124624,0.000000,NaN
1,AANobbMI,Sodium,2026-09-04 17:50:20.368359-07:00,220091956,218493006,1598950,64.518333,24782.878252,0.000000,0.000000,NaN
813607,I9W1u5Ac,Project: MCSR Ranked,2026-08-21 18:49:04.682461-07:00,1879315,1874780,4535,1.749722,2591.839975,NaN,NaN,NaN
765371,I9W1u5Ac,Project: MCSR Ranked,2026-08-21 18:56:59.493730-07:00,1879315,1879315,0,0.131944,0.000000,2591.839975,NaN,NaN
692605,I9W1u5Ac,Project: MCSR Ranked,2026-08-21 19:07:50.310225-07:00,1879315,1879315,0,0.180833,0.000000,0.000000,NaN,NaN
595749,I9W1u5Ac,Project: MCSR Ranked,2026-08-24 17:25:04.729335-07:00,1892042,1879315,12727,70.287222,181.071318,0.000000,0.000000,NaN
543161,I9W1u5Ac,Project: MCSR Ranked,2026-08-24 21:46:49.053741-07:00,1892042,1892042,0,4.362500,0.000000,181.071318,90.535659,0.000000
469963,I9W1u5Ac,Project: MCSR Ranked,2026-08-25 00:13:14.438090-07:00,1892042,1892042,0,2.440278,0.000000,0.000000,0.000000,NaN
374697,I9W1u5Ac,Project: MCSR Ranked,2026-08-25 14:27:30.458835-07:00,1893592,1892042,1550,14.237778,108.865304,0.000000,0.000000,NaN
302167,I9W1u5Ac,Project: MCSR Ranked,2026-08-25 19:35:36.229194-07:00,1905927,1893592,12335,5.135000,2402.142162,108.865304,0.000000,NaN
250547,I9W1u5Ac,Project: MCSR Ranked,2026-08-26 06:00:44.010241-07:00,1905927,1905927,0,10.418889,0.000000,2402.142162,0.000000,NaN
222319,I9W1u5Ac,Project: MCSR Ranked,2026-08-27 21:11:46.071527-07:00,1918711,1905927,12784,39.183889,326.256540,0.000000,0.000000,NaN
149137,I9W1u5Ac,Project: MCSR Ranked,2026-09-02 01:07:19.439631-07:00,1951815,1918711,33104,123.925833,267.127516,326.256540,108.865304,2.453743
100006,I9W1u5Ac,Project: MCSR Ranked,2026-09-02 01:19:14.161295-07:00,1951815,1951815,0,0.198611,0.000000,267.127516,108.865304,0.000000
464,I9W1u5Ac,Project: MCSR Ranked,2026-09-04 17:50:20.368359-07:00,1992041,1951815,40226,64.518333,623.481698,0.000000,108.865304,5.727093
815850,SIG65WOL,MaceBot,2026-08-21 18:49:04.682461-07:00,70952,70248,704,1.749722,402.349579,NaN,NaN,NaN
767068,SIG65WOL,MaceBot,2026-08-21 18:56:59.493730-07:00,70952,70952,0,0.131944,0.000000,402.349579,NaN,NaN
694267,SIG65WOL,MaceBot,2026-08-21 19:07:50.310225-07:00,70952,70952,0,0.180833,0.000000,0.000000,NaN,NaN
597998,SIG65WOL,MaceBot,2026-08-24 17:25:04.729335-07:00,73046,70952,2094,70.287222,29.792044,0.000000,0.000000,NaN
521031,SIG65WOL,MaceBot,2026-08-24 21:46:49.053741-07:00,73108,73046,62,4.362500,14.212034,29.792044,14.896022,0.954083
447883,SIG65WOL,MaceBot,2026-08-25 00:13:14.438090-07:00,73110,73108,2,2.440278,0.819579,14.212034,14.212034,0.057668
402695,SIG65WOL,MaceBot,2026-08-25 14:27:30.458835-07:00,73110,73110,0,14.237778,0.000000,0.819579,7.515807,0.000000
305395,SIG65WOL,MaceBot,2026-08-25 19:35:36.229194-07:00,73719,73110,609,5.135000,118.597858,0.000000,0.819579,144.705858
256229,SIG65WOL,MaceBot,2026-08-26 06:00:44.010241-07:00,73719,73719,0,10.418889,0.000000,118.597858,0.819579,0.000000
224795,SIG65WOL,MaceBot,2026-08-27 21:11:46.071527-07:00,75018,73719,1299,39.183889,33.151380,0.000000,0.819579,40.449288
151690,SIG65WOL,MaceBot,2026-09-02 01:07:19.439631-07:00,78498,75018,3480,123.925833,28.081312,33.151380,14.212034,1.975883
102334,SIG65WOL,MaceBot,2026-09-02 01:19:14.161295-07:00,78498,78498,0,0.198611,0.000000,28.081312,14.212034,0.000000
3416,SIG65WOL,MaceBot,2026-09-04 17:50:20.368359-07:00,80375,78498,1877,64.518333,29.092506,0.000000,0.819579,35.496898
812324,Xy8aRQKS,Physics Mod,2026-08-21 18:49:04.682461-07:00,21971881,21907227,64654,1.749722,36951.008097,NaN,NaN,NaN
763943,Xy8aRQKS,Physics Mod,2026-08-21 18:56:59.493730-07:00,21971881,21971881,0,0.131944,0.000000,36951.008097,NaN,NaN
691227,Xy8aRQKS,Physics Mod,2026-08-21 19:07:50.310225-07:00,21971881,21971881,0,0.180833,0.000000,0.000000,NaN,NaN
594290,Xy8aRQKS,Physics Mod,2026-08-24 17:25:04.729335-07:00,22164310,21971881,192429,70.287222,2737.752239,0.000000,0.000000,NaN
544966,Xy8aRQKS,Physics Mod,2026-08-24 21:46:49.053741-07:00,22164310,22164310,0,4.362500,0.000000,2737.752239,1368.876119,0.000000
471768,Xy8aRQKS,Physics Mod,2026-08-25 00:13:14.438090-07:00,22164310,22164310,0,2.440278,0.000000,0.000000,0.000000,NaN
374662,Xy8aRQKS,Physics Mod,2026-08-25 14:27:30.458835-07:00,22224417,22164310,60107,14.237778,4221.656001,0.000000,0.000000,NaN
303678,Xy8aRQKS,Physics Mod,2026-08-25 19:35:36.229194-07:00,22226484,22224417,2067,5.135000,402.531646,4221.656001,0.000000,NaN
253167,Xy8aRQKS,Physics Mod,2026-08-26 06:00:44.010241-07:00,22226484,22226484,0,10.418889,0.000000,402.531646,0.000000,NaN
221369,Xy8aRQKS,Physics Mod,2026-08-27 21:11:46.071527-07:00,22343996,22226484,117512,39.183889,2998.987679,0.000000,0.000000,NaN
148216,Xy8aRQKS,Physics Mod,2026-09-02 01:07:19.439631-07:00,22620679,22343996,276683,123.925833,2232.649905,2998.987679,402.531646,5.546520
98697,Xy8aRQKS,Physics Mod,2026-09-02 01:19:14.161295-07:00,22620679,22620679,0,0.198611,0.000000,2232.649905,402.531646,0.000000
160,Xy8aRQKS,Physics Mod,2026-09-04 17:50:20.368359-07:00,22732430,22620679,111751,64.518333,1732.081321,0.000000,402.531646,4.302969

In [38]:
run_interval_df = (
    project_download_metrics_df[
        [
            "run_id",
            "run_rank",
            "observed_at",
        ]
    ]
    .drop_duplicates()
    .sort_values("observed_at")
)

run_interval_df["hours_since_previous_run"] = (
    run_interval_df["observed_at"]
    .diff()
    .dt.total_seconds()
    / 3600
)

run_interval_df

,run_id,run_rank,observed_at,hours_since_previous_run
831182,f7d7af7d-e9a1-4bfe-9649-86faf2dcdcb4,13,2026-08-21 18:49:04.682461-07:00,NaN
746387,51dc50b7-6533-4816-bb25-2cc17c3d9dc9,12,2026-08-21 18:56:59.493730-07:00,0.131892
673242,21f1554d-0f8b-423c-b708-97f80453e17f,11,2026-08-21 19:07:50.310225-07:00,0.180782
609767,3b497402-8609-42e3-9304-38aadd1066f4,10,2026-08-24 17:25:04.729335-07:00,70.287339
530244,807ef283-b059-48b3-b90c-3f3f1dde2396,9,2026-08-24 21:46:49.053741-07:00,4.362312
457075,0a0fa12b-0c4d-415c-bad1-9d83d97629e4,8,2026-08-25 00:13:14.438090-07:00,2.440385
384481,8af5da09-b203-4d7e-bcab-e78002bb8f35,7,2026-08-25 14:27:30.458835-07:00,14.237784
320193,714895d5-1e06-4159-861f-77973a3476b8,6,2026-08-25 19:35:36.229194-07:00,5.134936
236916,8235114d-455f-4360-bb4d-dc5c73bc33ff,5,2026-08-26 06:00:44.010241-07:00,10.418828
223875,e487bcd0-ffbf-4078-b381-e796fdd81418,4,2026-08-27 21:11:46.071527-07:00,39.183906
163619,10f53270-9e39-48b1-af29-169eb70358f6,3,2026-09-02 01:07:19.439631-07:00,123.925936
82484,092bbf2a-b760-4b98-a2c2-4fe94ecdc48b,2,2026-09-02 01:19:14.161295-07:00,0.198534
15537,7fd9fb62-16c2-41c9-99e0-f87dae832968,1,2026-09-04 17:50:20.368359-07:00,64.518391

In [39]:
trend_metrics_query = """
    WITH run_summary AS (
        SELECT
            run_id,
            MAX(c_pull_timestamp_utc) AS observed_at,
            COUNT(DISTINCT project_id) AS project_count

        FROM modrinth_project_listings

        WHERE project_type = 'mod'

        GROUP BY
            run_id
    ),

    current_run AS (
        SELECT
            run_id,
            observed_at

        FROM run_summary

        ORDER BY
            observed_at DESC,
            run_id DESC

        LIMIT 1
    ),

    comparison_run AS (
        SELECT
            r.run_id,
            r.observed_at

        FROM run_summary AS r

        CROSS JOIN current_run AS c

        WHERE r.observed_at <= (
            c.observed_at - INTERVAL '24 hours'
        )

        ORDER BY
            r.observed_at DESC,
            r.run_id DESC

        LIMIT 1
    ),

    baseline_run AS (
        SELECT
            r.run_id,
            r.observed_at

        FROM run_summary AS r

        CROSS JOIN comparison_run AS c

        WHERE r.observed_at <= (
            c.observed_at - INTERVAL '7 days'
        )

        ORDER BY
            r.observed_at DESC,
            r.run_id DESC

        LIMIT 1
    ),

    selected_runs AS (
        SELECT
            run_id,
            observed_at,
            'current' AS snapshot

        FROM current_run

        UNION ALL

        SELECT
            run_id,
            observed_at,
            'comparison' AS snapshot

        FROM comparison_run

        UNION ALL

        SELECT
            run_id,
            observed_at,
            'baseline' AS snapshot

        FROM baseline_run
    ),

    project_snapshots AS (
        SELECT
            s.snapshot,
            s.observed_at,

            p.project_id,

            JSON_EXTRACT_STRING(
                p.payload,
                '$.title'
            ) AS title,

            TRY_CAST(
                JSON_EXTRACT_STRING(
                    p.payload,
                    '$.downloads'
                )
                AS BIGINT
            ) AS total_downloads,

            ROW_NUMBER() OVER (
                PARTITION BY
                    s.snapshot,
                    p.project_id

                ORDER BY
                    p.c_pull_timestamp_utc DESC
            ) AS row_num

        FROM modrinth_project_listings AS p

        INNER JOIN selected_runs AS s
            ON p.run_id = s.run_id

        WHERE p.project_type = 'mod'
    ),

    deduped_snapshots AS (
        SELECT
            snapshot,
            observed_at,
            project_id,
            title,
            total_downloads

        FROM project_snapshots

        WHERE row_num = 1
    ),

    pivoted_snapshots AS (
        SELECT
            project_id,

            MAX(title) FILTER (
                WHERE snapshot = 'current'
            ) AS title,

            MAX(total_downloads) FILTER (
                WHERE snapshot = 'current'
            ) AS current_downloads,

            MAX(total_downloads) FILTER (
                WHERE snapshot = 'comparison'
            ) AS comparison_downloads,

            MAX(total_downloads) FILTER (
                WHERE snapshot = 'baseline'
            ) AS baseline_downloads,

            MAX(observed_at) FILTER (
                WHERE snapshot = 'current'
            ) AS current_observed_at,

            MAX(observed_at) FILTER (
                WHERE snapshot = 'comparison'
            ) AS comparison_observed_at,

            MAX(observed_at) FILTER (
                WHERE snapshot = 'baseline'
            ) AS baseline_observed_at

        FROM deduped_snapshots

        GROUP BY
            project_id
    ),

    calculated_metrics AS (
        SELECT
            *,

            current_downloads
                - comparison_downloads
                AS current_downloads_gained,

            comparison_downloads
                - baseline_downloads
                AS baseline_downloads_gained,

            DATE_DIFF(
                'second',
                comparison_observed_at,
                current_observed_at
            ) / 3600.0
                AS current_hours,

            DATE_DIFF(
                'second',
                baseline_observed_at,
                comparison_observed_at
            ) / 3600.0
                AS baseline_hours

        FROM pivoted_snapshots

        WHERE current_downloads IS NOT NULL
          AND comparison_downloads IS NOT NULL
          AND baseline_downloads IS NOT NULL
    )

    SELECT
        project_id,
        title,

        current_downloads,

        current_downloads_gained,
        baseline_downloads_gained,

        current_hours,
        baseline_hours,

        current_downloads_gained
            / NULLIF(current_hours, 0)
            AS current_velocity,

        baseline_downloads_gained
            / NULLIF(baseline_hours, 0)
            AS baseline_velocity,

        (
            current_downloads_gained
            / NULLIF(current_hours, 0)
        )
        /
        NULLIF(
            baseline_downloads_gained
            / NULLIF(baseline_hours, 0),
            0
        ) AS velocity_ratio

    FROM calculated_metrics

    WHERE current_downloads_gained >= 0
      AND baseline_downloads_gained >= 0

    ORDER BY
        velocity_ratio DESC
"""

In [42]:
with duckdb.connect(modrinth_bronze_path, read_only=True) as bronze_con:
    trend_metrics_df = bronze_con.execute(trend_metrics_query).fetch_df()

In [43]:
trend_metrics_df.head(30)

,project_id,title,current_downloads,current_downloads_gained,baseline_downloads_gained,current_hours,baseline_hours,current_velocity,baseline_velocity,velocity_ratio
0,UyHm1t8d,Random Respawn,1250,854,10,64.518333,173.727222,13.236548,0.057562,229.954867
1,yXbLlSQN,Scaling Mobs,3117,875,23,64.518333,173.727222,13.562037,0.132391,102.438911
2,561gHy1d,TabAPI,5903,825,43,64.518333,173.727222,12.787063,0.247514,51.661883
3,L4MwdPaO,Attribute Backport,7122,929,50,64.518333,173.727222,14.399008,0.287808,50.029993
4,6dCeBfdr,ChatTweaker,260,16,1,64.518333,173.727222,0.247992,0.005756,43.082879
5,NtdHRxOb,Infrastructury,2972,61,4,64.518333,173.727222,0.945468,0.023025,41.063369
6,tgz8bnNz,Totem on Death,434,30,2,64.518333,173.727222,0.464984,0.011512,40.390199
7,VwyK8jq2,Arsonage,154,15,1,64.518333,173.727222,0.232492,0.005756,40.390199
8,bi7rhFz3,SkillZ,5119,867,60,64.518333,173.727222,13.438041,0.345369,38.909225
9,PkYtepFd,Funny Graveyards,79,14,1,64.518333,173.727222,0.216993,0.005756,37.697519
10,oo5RpOZF,APS Story,228,28,2,64.518333,173.727222,0.433985,0.011512,37.697519
11,VSI0sAPX,Simple Greenhouses,391,14,1,64.518333,173.727222,0.216993,0.005756,37.697519
12,wAYV14k6,Item Group Creator,183,42,3,64.518333,173.727222,0.650978,0.017268,37.697519
13,oLTa2VMm,Coral,386,27,2,64.518333,173.727222,0.418486,0.011512,36.351179
14,C67G4Yf3,Advancements for everything,201,13,1,64.518333,173.727222,0.201493,0.005756,35.004839
15,r2w0mBXt,KeepInventoryElse,129,13,1,64.518333,173.727222,0.201493,0.005756,35.004839
16,iG6ou6Sj,Realistic Torches [Plus],7078,903,73,64.518333,173.727222,13.996022,0.420199,33.308082
17,2sYzwpz4,Rewarding,414,12,1,64.518333,173.727222,0.185994,0.005756,32.312159
18,ULMJmwvU,Territorial,217,12,1,64.518333,173.727222,0.185994,0.005756,32.312159
19,CSKdjzLF,Brick Lib API,656,23,2,64.518333,173.727222,0.356488,0.011512,30.965819
20,tJF26Rgv,UltraLib,17823,880,77,64.518333,173.727222,13.639534,0.443224,30.773485
21,xJ7G5MjR,Enchanting Vanilla,7060,78,7,64.518333,173.727222,1.208959,0.040293,30.004148
22,g07Z9mbZ,Ender Pearl Craft 2,470,11,1,64.518333,173.727222,0.170494,0.005756,29.619479
23,taLQXG9B,EffectMaster,283,11,1,64.518333,173.727222,0.170494,0.005756,29.619479
24,wqsbtL6W,NX backup,172,11,1,64.518333,173.727222,0.170494,0.005756,29.619479
25,zflCFUw2,ramosy's Drivable Chicken,379,21,2,64.518333,173.727222,0.325489,0.011512,28.273139
26,dQ1rpWjI,DAHUD - Hud Medieval,418,10,1,64.518333,173.727222,0.154995,0.005756,26.926799
27,DFyq5FAS,Arrows Recovery,119,10,1,64.518333,173.727222,0.154995,0.005756,26.926799
28,GlReZwZN,TabChannel,241,58,6,64.518333,173.727222,0.898969,0.034537,26.029239
29,P4DIVmy2,Party Poppers,120,38,4,64.518333,173.727222,0.588980,0.023025,25.580459

In [44]:
trending_mods_df = (
    trend_metrics_df[
        (trend_metrics_df["current_downloads_gained"] >= 1_000)
        & (trend_metrics_df["baseline_velocity"] > 0)
    ]
    .sort_values(
        "velocity_ratio",
        ascending=False,
    )
)

In [45]:
trending_mods_df[
    [
        "project_id",
        "title",
        "current_downloads",
        "current_downloads_gained",
        "current_velocity",
        "baseline_velocity",
        "velocity_ratio",
    ]
].head(30)

,project_id,title,current_downloads,current_downloads_gained,current_velocity,baseline_velocity,velocity_ratio
255,s4WQHerM,3D Maps,6191,3774,58.495001,5.382001,10.868635
969,j9jxyR07,Yahiraft,4601,2674,41.445584,5.658296,7.324747
1254,JWEYmR12,Pastek's Lucky Block,10494,4196,65.035778,10.746733,6.051679
1293,ROwCMI9N,Integrated Lucky Blocks,21559,4066,63.020847,10.821563,5.823637
1294,bxNeVD9o,Redecorate,8681,1103,17.095916,2.947149,5.800832
1323,b0C4QetW,Stone Lucky Block,12125,4606,71.390561,13.124023,5.439686
2443,TsQgSXVF,The Forest Anomaly,19235,1011,15.669965,2.987442,5.245278
2473,PacPygzz,Hypixel Lucky Blocks,43907,10898,168.913229,33.454745,5.049007
2482,ETYqWHa5,Dungeons+: More Spawners,83609,1032,15.995453,3.171639,5.043277
2526,PsY5btQe,Potion API,24798,8071,125.096226,25.712723,4.865149
2661,NysbPTkh,Legend of the Lucky Blocks,39189,12068,187.047609,39.855585,4.693134
2680,OQ8To4FT,Disenchanter,208722,1074,16.646431,3.597594,4.627101
2723,IGRcH1wA,Rainbow Lucky Block,22109,4820,74.707447,16.583469,4.504935
3044,lvtoSiQS,Iden's Decor,8019,1070,16.584433,3.931451,4.218400
3756,fB1gJLGX,e4all,153369,23316,361.385653,89.582967,4.034089
3781,95Rx81bQ,Treasures of the dead,20676,1964,30.440960,7.695973,3.955440
3835,q38mmH7i,LDShadowLady's Disney Wish Rebrushed,19473,4630,71.762548,18.477242,3.883834
3894,zRIA8Bvc,Nautilus Studio - Packs Editor IDE,5296,1208,18.723360,4.881215,3.835799
3930,JxyIfnWu,Critters n' Crawlers,104922,2687,41.647077,11.034540,3.774247
5006,19P0GlZk,Enhanced Celestials 2: Default Lunar Events,13689,3209,49.737801,14.839355,3.351749
5019,UILFr9Hb,Skeleton Ghost Ship,19655,1825,28.286534,8.478809,3.336145
5393,wlLhCabV,Unbound Fov,66470,1073,16.630932,5.203560,3.196068
5475,6cEnKtmZ,Enhanced Celestials 2: Shader Support,9608,2149,33.308362,10.545267,3.158608
5478,WaCchT6K,Myths of The Sea,58586,3148,48.792333,15.501313,3.147626
6004,eHe8QhtD,Compose Multiplatform,144741,17616,273.038671,91.436447,2.986103
6367,SRDQqMfX,Roughly Enough Trades,187813,1385,21.466767,7.598118,2.825274
6502,yBLrXpfD,Sky's Overworld Quartz,48933,1226,19.002351,6.821038,2.785844
6527,AibBIVmj,OneConfig,557197,34610,536.436672,193.481480,2.772548
6542,KvsvCJwP,Christmas Lucky Block,32986,6264,97.088683,35.239152,2.755137
6554,E86423bk,Flyspeed (Creative Flight),115725,1762,27.310067,10.079019,2.709596

In [46]:
trend_candidates_df = (
    trend_metrics_df[
        (trend_metrics_df["baseline_velocity"] > 0)
        & (trend_metrics_df["current_downloads_gained"] >= 1_000)
        & (trend_metrics_df["velocity_ratio"] > 1)
    ]
    .copy()
)

In [47]:
trend_candidates_df["velocity_ratio_percentile"] = (
    trend_candidates_df["velocity_ratio"]
    .rank(
        pct=True,
        method="average",
    )
)

trend_candidates_df["download_gain_percentile"] = (
    trend_candidates_df["current_downloads_gained"]
    .rank(
        pct=True,
        method="average",
    )
)

In [48]:
trend_candidates_df["trend_score"] = (
    100
    * (
        2
        * trend_candidates_df["velocity_ratio_percentile"]
        * trend_candidates_df["download_gain_percentile"]
    )
    / (
        trend_candidates_df["velocity_ratio_percentile"]
        + trend_candidates_df["download_gain_percentile"]
    )
)

In [49]:
trending_ranked_df = (
    trend_candidates_df
    .sort_values(
        "trend_score",
        ascending=False,
    )
    .reset_index(drop=True)
)

trending_ranked_df["trend_rank"] = (
    trending_ranked_df.index + 1
)

In [50]:
trending_ranked_df["velocity_lift"] = (
    trending_ranked_df["current_velocity"]
    - trending_ranked_df["baseline_velocity"]
)

In [51]:
trending_ranked_df[
    [
        "trend_rank",
        "project_id",
        "title",
        "current_downloads",
        "current_downloads_gained",
        "current_velocity",
        "baseline_velocity",
        "velocity_ratio",
        "velocity_ratio_percentile",
        "velocity_lift",
        "download_gain_percentile",
        "trend_score",
    ]
].head(30)

,trend_rank,project_id,title,current_downloads,current_downloads_gained,current_velocity,baseline_velocity,velocity_ratio,velocity_ratio_percentile,velocity_lift,download_gain_percentile,trend_score
0,1,I9W1u5Ac,Project: MCSR Ranked,1992041,40226,623.481698,264.138224,2.360437,0.975393,359.343473,0.933698,95.409014
1,2,AibBIVmj,OneConfig,557197,34610,536.436672,193.481480,2.772548,0.981545,342.955192,0.917293,94.833195
2,3,y6DuFGwJ,Skyblocker • Hypixel Skyblock,4566123,63682,987.037276,633.280142,1.558611,0.930964,353.757134,0.959672,94.509988
3,4,jJJLywXp,Odin - Hypixel Skyblock,1427513,34786,539.164579,306.273244,1.760404,0.962406,232.891334,0.918660,94.002448
4,5,IMuO8COj,[ESF] Entity Sound Features,2567675,28437,440.758441,236.197871,1.866056,0.967874,204.560570,0.904990,93.537626
5,6,fB1gJLGX,e4all,153369,23316,361.385653,89.582967,4.034089,0.990431,271.802686,0.884484,93.446389
6,7,UR0ocuEt,NBT Autocomplete,1400184,28400,440.184960,250.001119,1.760732,0.963090,190.183841,0.904306,93.277267
7,8,AtOSAunf,Optimized Block Entities [OBE],1011781,67042,1039.115497,761.958882,1.363742,0.889952,277.156615,0.961039,92.413052
8,9,eHe8QhtD,Compose Multiplatform,144741,17616,273.038671,91.436447,2.986103,0.983595,181.602224,0.858510,91.680576
9,10,2Uev7LdA,LambdaBetterGrass,1650706,18272,283.206324,166.830504,1.697569,0.958988,116.375820,0.863295,90.862890
10,11,Br0kXPwc,Tensura: Reincarnated,1465376,15210,235.746945,126.623794,1.861790,0.967191,109.123151,0.838004,89.797486
11,12,6avVoBVB,Simply Tooltips,384577,25635,397.328925,282.414002,1.406902,0.899522,114.914923,0.896104,89.780946
12,13,wRRSWpd1,ManasCore,1239824,19007,294.598435,197.211465,1.493820,0.915926,97.386970,0.867396,89.100063
13,14,bjvFzLV3,Tensura: Mysticism,1043681,16045,248.689003,157.753055,1.576445,0.937116,90.935948,0.844156,88.821002
14,15,NysbPTkh,Legend of the Lucky Blocks,39189,12068,187.047609,39.855585,4.693134,0.993165,147.192025,0.802119,88.747673
15,16,PacPygzz,Hypixel Lucky Blocks,43907,10898,168.913229,33.454745,5.049007,0.995215,135.458483,0.777170,87.278042
16,17,zy0karK1,Animatium,578509,14758,228.741185,155.617523,1.469893,0.909091,73.123662,0.835270,87.061841
17,18,1aD7nY4F,Tensura: Better Subordinates,319143,11972,185.559660,111.525412,1.663833,0.954887,74.034248,0.799727,87.044647
18,19,PcmQvtAt,Tensura: SlimeThrone Extras,630551,16883,261.677559,192.197858,1.361501,0.887218,69.479701,0.850991,86.872707
19,20,oLS8HdJ1,Streams Reflowing,174094,16557,256.624732,188.462117,1.361678,0.887902,68.162615,0.847573,86.726896
20,21,8pJYUDNi,Chatting,1677633,13882,215.163649,150.442744,1.430203,0.903623,64.720905,0.826384,86.327921
21,22,P1OZGk5p,ViaVersion,2907830,28456,441.052931,352.552693,1.251027,0.823650,88.500238,0.905673,86.271644
22,23,N6n5dqoA,Axiom,12519968,119767,1856.325076,1548.968530,1.198427,0.767601,307.356546,0.980861,86.122531
23,24,Kw7Sm3Xf,Noxesium,8302058,24479,379.411537,303.003751,1.252168,0.824334,76.407786,0.891319,85.651870
24,25,xUTHly0N,Centered Crosshair,1600036,14316,221.890419,167.550023,1.324323,0.873548,54.340396,0.829118,85.075321
25,26,ODKaullJ,Tensura: Not Enough Bosses,678908,11131,172.524605,112.135564,1.538536,0.925496,60.389042,0.781271,84.728989
26,27,NpvuJQoq,ViaBackwards,1955936,18990,294.334944,235.484108,1.249914,0.821599,58.850835,0.866712,84.355312
27,28,8aoMKplv,Punchy!,4262447,112686,1746.573325,1491.930837,1.170680,0.729323,254.642489,0.980178,83.634516
28,29,bFBJU91s,MouseTweaks x Accessories Fix,450630,15887,246.240087,196.135065,1.255462,0.826384,50.105022,0.843472,83.484080
29,30,h1E7sQNL,Customizable Player Models,2892383,17699,274.325127,221.456370,1.238732,0.809979,52.868757,0.859877,83.418273