In [4]:
import duckdb
from minecraft_data_dashboard.utils.db import (
    get_modrinth_overview_kpis,
    get_project_type_distribution,
    get_modrinth_project_listings_time_series,
    get_modrinth_overview_preview,
)

In [6]:
with duckdb.connect('/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||api.modrinth.com.duckdb') as bronze_con:
    df = bronze_con.execute("SELECT * FROM ingestion_log").fetch_df()
df

,run_id,ingestion_type,api_url,project_type,status,records_processed,records_written,records_failed,records_skipped,nested_records_fetched,failed_record_ids,skipped_record_ids,error_message,start_time,end_time,duration_seconds
0,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,mod,success,73499,72802,0,697,<NA>,<NA>,"[t3qEwmQm, t9urSl1Z, bApGjY4X, inmPbeHN, jxktW...",None,2026-08-21 19:04:29.140258-07:00,2026-08-21 19:07:50.757651-07:00,201.617393
1,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,modpack,success,18136,18119,0,17,<NA>,<NA>,"[rpQjGciW, jrguFbWu, 8AciRjot, OUOIQAoj, OheBI...",None,2026-08-21 19:07:50.800712-07:00,2026-08-21 19:08:12.385967-07:00,21.585255
2,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,resourcepack,success,33192,32972,0,220,<NA>,<NA>,"[mzDVxkyK, KXCVIm8S, JeJtzt8n, J1I1LqCu, 5X7Bq...",None,2026-08-21 19:08:12.429416-07:00,2026-08-21 19:09:03.669433-07:00,51.240017
3,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,shader,success,834,834,0,0,<NA>,<NA>,[],None,2026-08-21 19:09:03.712466-07:00,2026-08-21 19:09:04.597561-07:00,0.885095
4,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,plugin,success,17057,16849,0,208,<NA>,<NA>,"[s7cqsWbL, Prt907qL, rEq2hinY, r4AnTY0K, gnGqB...",None,2026-08-21 19:09:04.636947-07:00,2026-08-21 19:10:21.746641-07:00,77.109694
5,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,datapack,success,14211,14165,0,46,<NA>,<NA>,"[FwEv1xZe, VPqOBauJ, dtFq9Ajb, ZwxJCwYK, gtKDI...",None,2026-08-21 19:10:21.792474-07:00,2026-08-21 19:10:34.093725-07:00,12.301251
6,21f1554d-0f8b-423c-b708-97f80453e17f,project_listings,https://api.modrinth.com/v2,minecraft_java_server,success,2016,2016,0,0,<NA>,<NA>,[],None,2026-08-21 19:10:34.139368-07:00,2026-08-21 19:10:36.122585-07:00,1.983217
7,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,datapack,success,14165,14164,1,0,94120,<NA>,<NA>,None,NaT,NaT,2876.544429
8,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,minecraft_java_server,success,2016,2016,0,0,3632,<NA>,<NA>,None,NaT,NaT,409.856691
9,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,mod,success,72802,72787,15,0,952384,<NA>,<NA>,None,NaT,NaT,14996.706185
10,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,modpack,success,18119,18115,4,0,167093,<NA>,<NA>,None,NaT,NaT,4488.259150
11,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,plugin,success,16849,16847,2,0,113858,<NA>,<NA>,None,NaT,NaT,3504.086984
12,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,resourcepack,success,32972,32967,5,0,130865,<NA>,<NA>,None,NaT,NaT,6716.950382
13,9686352e-8206-416a-a615-74f4da8391aa,project_versions,https://api.modrinth.com/v2,shader,success,834,834,0,0,3767,<NA>,<NA>,None,NaT,NaT,169.920634
14,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,mod,success,73665,73251,0,414,<NA>,<NA>,"[fn5zBLFv, mjzL9n6c, ow5rRJYD, VIyfWZUN, 3fSYM...",None,2026-08-24 17:22:24.883195-07:00,2026-08-24 17:25:04.963579-07:00,160.080384
15,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,modpack,success,18122,18114,0,8,<NA>,<NA>,"[lLvt7Ikn, 2OsDXf3Y, nOoGx7HO, Yg54xcoi, 5qgLy...",None,2026-08-24 17:25:05.017950-07:00,2026-08-24 17:25:23.158597-07:00,18.140647
16,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,resourcepack,success,33380,33120,0,260,<NA>,<NA>,"[yNMNbi6t, 7vYYzLWr, mZyY7wUm, 9X0VcGnx, SyCm2...",None,2026-08-24 17:25:23.208891-07:00,2026-08-24 17:27:08.196069-07:00,104.987178
17,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,shader,success,836,836,0,0,<NA>,<NA>,[],None,2026-08-24 17:27:08.245817-07:00,2026-08-24 17:27:09.263757-07:00,1.017940
18,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,plugin,success,17084,16868,0,216,<NA>,<NA>,"[WNd0pom2, mxLY4YNr, bSapjIA6, IpPMylIy, ir0id...",None,2026-08-24 17:27:09.309207-07:00,2026-08-24 17:27:25.093766-07:00,15.784559
19,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,datapack,success,14212,14166,0,46,<NA>,<NA>,"[T1KxDMSy, eF0tSR7M, z97mOnkJ, PCKzcyYw, ylynA...",None,2026-08-24 17:27:25.146454-07:00,2026-08-24 17:28:37.946572-07:00,72.800118
20,3b497402-8609-42e3-9304-38aadd1066f4,project_listings,https://api.modrinth.com/v2,minecraft_java_server,success,1978,1978,0,0,<NA>,<NA>,[],None,2026-08-24 17:28:37.998345-07:00,2026-08-24 17:28:39.556034-07:00,1.557689
21,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,mod,success,73695,73183,0,512,<NA>,<NA>,"[fn5zBLFv, mjzL9n6c, ow5rRJYD, VIyfWZUN, 3fSYM...",None,2026-08-24 21:43:38.633729-07:00,2026-08-24 21:46:49.299326-07:00,190.665597
22,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,modpack,success,18121,18114,0,7,<NA>,<NA>,"[2OsDXf3Y, nOoGx7HO, Yg54xcoi, 5qgLyzW4, 7T8Yi...",None,2026-08-24 21:46:49.347690-07:00,2026-08-24 21:47:11.359352-07:00,22.011662
23,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,resourcepack,success,33458,33200,0,258,<NA>,<NA>,"[yNMNbi6t, 7vYYzLWr, 88VX3Fcq, 7ef7ETMg, 9X0Vc...",None,2026-08-24 21:47:11.400810-07:00,2026-08-24 21:48:59.399845-07:00,107.999035
24,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,shader,success,836,836,0,0,<NA>,<NA>,[],None,2026-08-24 21:48:59.424036-07:00,2026-08-24 21:49:00.074868-07:00,0.650832
25,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,plugin,success,17085,16867,0,218,<NA>,<NA>,"[WNd0pom2, mxLY4YNr, bSapjIA6, IpPMylIy, ir0id...",None,2026-08-24 21:49:00.096807-07:00,2026-08-24 21:49:18.440980-07:00,18.344173
26,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,datapack,success,14211,14165,0,46,<NA>,<NA>,"[T1KxDMSy, hEz3emYh, z97mOnkJ, PCKzcyYw, ylynA...",None,2026-08-24 21:49:18.467776-07:00,2026-08-24 21:49:29.302147-07:00,10.834371
27,807ef283-b059-48b3-b90c-3f3f1dde2396,project_listings,https://api.modrinth.com/v2,minecraft_java_server,success,1977,1977,0,0,<NA>,<NA>,[],None,2026-08-24 21:49:29.326325-07:00,2026-08-24 21:49:30.926795-07:00,1.600470

In [7]:
with duckdb.connect('/Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/https:||api.modrinth.com.duckdb') as bronze_con:
    df = bronze_con.execute("SELECT * FROM modrinth_project_listings LIMIT 20").fetch_df()
df

,run_id,project_type,project_id,payload,c_pull_timestamp_utc
0,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,P7dR8mSH,"{""project_id"": ""P7dR8mSH"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
1,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,AANobbMI,"{""project_id"": ""AANobbMI"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
2,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,YL57xq9U,"{""project_id"": ""YL57xq9U"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
3,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,9s6osm5g,"{""project_id"": ""9s6osm5g"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
4,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,NNAgCjsB,"{""project_id"": ""NNAgCjsB"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
5,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,uXXizFIs,"{""project_id"": ""uXXizFIs"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
6,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,mOgUt4GM,"{""project_id"": ""mOgUt4GM"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
7,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,gvQqBUqZ,"{""project_id"": ""gvQqBUqZ"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
8,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,5ZwdcRci,"{""project_id"": ""5ZwdcRci"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
9,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,1eAoo2KR,"{""project_id"": ""1eAoo2KR"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
10,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,Ha28R6CL,"{""project_id"": ""Ha28R6CL"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
11,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,1bokaNcj,"{""project_id"": ""1bokaNcj"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
12,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,BVzZfTc1,"{""project_id"": ""BVzZfTc1"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
13,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,lhGA9TYQ,"{""project_id"": ""lhGA9TYQ"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
14,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,NcUtCpym,"{""project_id"": ""NcUtCpym"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
15,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,PtjYWJkn,"{""project_id"": ""PtjYWJkn"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
16,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,4I1XuqiY,"{""project_id"": ""4I1XuqiY"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
17,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,EsAfCjCV,"{""project_id"": ""EsAfCjCV"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
18,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,MPCX6s5C,"{""project_id"": ""MPCX6s5C"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00
19,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,Bh37bMuy,"{""project_id"": ""Bh37bMuy"", ""project_type"": ""mo...",2026-08-21 17:00:58.131666-07:00

In [3]:
df = get_modrinth_project_listings_time_series()
df

,run_id,project_type,pull_date,project_count
0,21f1554d-0f8b-423c-b708-97f80453e17f,datapack,2026-08-21,14165
1,21f1554d-0f8b-423c-b708-97f80453e17f,minecraft_java_server,2026-08-21,2016
2,5bdf61cd-ca8a-47cc-ac3b-e00eb7fe15cc,mod,2026-08-21,72761
3,21f1554d-0f8b-423c-b708-97f80453e17f,mod,2026-08-21,72802
4,f7d7af7d-e9a1-4bfe-9649-86faf2dcdcb4,mod,2026-08-21,72800
5,51dc50b7-6533-4816-bb25-2cc17c3d9dc9,mod,2026-08-21,72802
6,21f1554d-0f8b-423c-b708-97f80453e17f,modpack,2026-08-21,18119
7,21f1554d-0f8b-423c-b708-97f80453e17f,plugin,2026-08-21,16849
8,21f1554d-0f8b-423c-b708-97f80453e17f,resourcepack,2026-08-21,32972
9,21f1554d-0f8b-423c-b708-97f80453e17f,shader,2026-08-21,834
10,807ef283-b059-48b3-b90c-3f3f1dde2396,datapack,2026-08-24,14165
11,3b497402-8609-42e3-9304-38aadd1066f4,datapack,2026-08-24,14166
12,807ef283-b059-48b3-b90c-3f3f1dde2396,minecraft_java_server,2026-08-24,1977
13,3b497402-8609-42e3-9304-38aadd1066f4,minecraft_java_server,2026-08-24,1978
14,807ef283-b059-48b3-b90c-3f3f1dde2396,mod,2026-08-24,73183
15,3b497402-8609-42e3-9304-38aadd1066f4,mod,2026-08-24,73251
16,3b497402-8609-42e3-9304-38aadd1066f4,modpack,2026-08-24,18114
17,807ef283-b059-48b3-b90c-3f3f1dde2396,modpack,2026-08-24,18114
18,3b497402-8609-42e3-9304-38aadd1066f4,plugin,2026-08-24,16868
19,807ef283-b059-48b3-b90c-3f3f1dde2396,plugin,2026-08-24,16867
20,807ef283-b059-48b3-b90c-3f3f1dde2396,resourcepack,2026-08-24,33200
21,3b497402-8609-42e3-9304-38aadd1066f4,resourcepack,2026-08-24,33120
22,3b497402-8609-42e3-9304-38aadd1066f4,shader,2026-08-24,836
23,807ef283-b059-48b3-b90c-3f3f1dde2396,shader,2026-08-24,836